#ifndef __CUST_IMG_GROUP_SINGLE_THIRDROM_RES_H__
#define __CUST_IMG_GROUP_SINGLE_THIRDROM_RES_H__

#include "CustDataRes.h"
#include "ResCompressConfig.h"
#ifdef __MMI_RESOURCE_IMAGE_THIRD_ROM__
#ifndef  __MMI_RESOURCE_UT_UNCOMPRESSED_IMAGE_SUPPORT__

extern const U8 ________CUSTOMER__IMAGES__EMPTYIMAGE_BMP[];
extern const U8 ________CUSTOMER__IMAGES__DEFAULT_BMP[];
extern const U8 ________CUSTOMER__IMAGES__FTE_SLIM240X320__MAINLCD__WORLDCLOCK__MAP01_GIF[];
extern const U8 ________CUSTOMER__IMAGES__FTE_SLIM240X320__MAINLCD__CALL__CONNECT__CL_NET_PNG[];


#endif // __MMI_RESOURCE_UT_UNCOMPRESSED_IMAGE_SUPPORT__



#endif // __MMI_RESOURCE_IMAGE_THIRD_ROM__


#endif // __CUST_IMG_GROUP_SINGLE_THIRDROM_RES_H__
