/* This file is automatically generated by venus_theme_generator.pl. Do not modify it. */

#ifndef __CUST_VENUS_THEME_ID_H__
#define __CUST_VENUS_THEME_ID_H__

typedef struct
{	U8 hash_value;
	U16 id;
	const U8* str;
} mmi_res_thm_id_str_tbl_struct;

#define MMI_RES_THM_ALL_IMG_IDS 0
#define MMI_RES_THM_ALL_COL_IDS 15
#define MMI_RES_THM_ALL_FNT_IDS 0
#define MMI_RES_THM_ALL_INT_IDS 44
#define MMI_RES_THM_ALL_ADO_IDS 0
#define MMI_RES_THM_ALL_BIN_IDS 0

static const U8 g_mmi_res_thm_fe1_1_1_shadow_color_str[] = "FE1_1_1_SHADOW_COLOR";
static const U8 g_mmi_res_thm_fe1_1_2_shadow_color_str[] = "FE1_1_2_SHADOW_COLOR";
static const U8 g_mmi_res_thm_fe1_1_3_shadow_color_str[] = "FE1_1_3_SHADOW_COLOR";
static const U8 g_mmi_res_thm_fe1_1_4_shadow_color_str[] = "FE1_1_4_SHADOW_COLOR";
static const U8 g_mmi_res_thm_fe1_1_5_shadow_color_str[] = "FE1_1_5_SHADOW_COLOR";
static const U8 g_mmi_res_thm_fe1_1_6_shadow_color_str[] = "FE1_1_6_SHADOW_COLOR";
static const U8 g_mmi_res_thm_fe1_1_7_shadow_color_str[] = "FE1_1_7_SHADOW_COLOR";
static const U8 g_mmi_res_thm_fe1_1_8_shadow_color_str[] = "FE1_1_8_SHADOW_COLOR";
static const U8 g_mmi_res_thm_fe1_1_9_shadow_color_str[] = "FE1_1_9_SHADOW_COLOR";
static const U8 g_mmi_res_thm_fe2_2_3_outer_glow_color_str[] = "FE2_2_3_OUTER_GLOW_COLOR";
static const U8 g_mmi_res_thm_fe3_3_3_upper_engraved_color_str[] = "FE3_3_3_UPPER_ENGRAVED_COLOR";
static const U8 g_mmi_res_thm_fe3_3_4_lower_engraved_color_str[] = "FE3_3_4_LOWER_ENGRAVED_COLOR";
static const U8 g_mmi_res_thm_fe4_4_3_first_gradient_color_str[] = "FE4_4_3_FIRST_GRADIENT_COLOR";
static const U8 g_mmi_res_thm_fe4_4_4_second_gradient_color_str[] = "FE4_4_4_SECOND_GRADIENT_COLOR";
static const U8 g_mmi_res_thm_fe5_5_3_border_color_str[] = "FE5_5_3_BORDER_COLOR";
static const U8 g_mmi_res_thm_fe1_1_1_shadow_degree_str[] = "FE1_1_1_SHADOW_DEGREE";
static const U8 g_mmi_res_thm_fe1_1_1_shadow_distant_str[] = "FE1_1_1_SHADOW_DISTANT";
static const U8 g_mmi_res_thm_fe1_1_1_shadow_range_str[] = "FE1_1_1_SHADOW_RANGE";
static const U8 g_mmi_res_thm_fe1_1_1_shadow_transparency_str[] = "FE1_1_1_SHADOW_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe1_1_2_shadow_degree_str[] = "FE1_1_2_SHADOW_DEGREE";
static const U8 g_mmi_res_thm_fe1_1_2_shadow_distant_str[] = "FE1_1_2_SHADOW_DISTANT";
static const U8 g_mmi_res_thm_fe1_1_2_shadow_range_str[] = "FE1_1_2_SHADOW_RANGE";
static const U8 g_mmi_res_thm_fe1_1_2_shadow_transparency_str[] = "FE1_1_2_SHADOW_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe1_1_3_shadow_degree_str[] = "FE1_1_3_SHADOW_DEGREE";
static const U8 g_mmi_res_thm_fe1_1_3_shadow_distant_str[] = "FE1_1_3_SHADOW_DISTANT";
static const U8 g_mmi_res_thm_fe1_1_3_shadow_range_str[] = "FE1_1_3_SHADOW_RANGE";
static const U8 g_mmi_res_thm_fe1_1_3_shadow_transparency_str[] = "FE1_1_3_SHADOW_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe1_1_4_shadow_degree_str[] = "FE1_1_4_SHADOW_DEGREE";
static const U8 g_mmi_res_thm_fe1_1_4_shadow_distant_str[] = "FE1_1_4_SHADOW_DISTANT";
static const U8 g_mmi_res_thm_fe1_1_4_shadow_range_str[] = "FE1_1_4_SHADOW_RANGE";
static const U8 g_mmi_res_thm_fe1_1_4_shadow_transparency_str[] = "FE1_1_4_SHADOW_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe1_1_5_shadow_degree_str[] = "FE1_1_5_SHADOW_DEGREE";
static const U8 g_mmi_res_thm_fe1_1_5_shadow_distant_str[] = "FE1_1_5_SHADOW_DISTANT";
static const U8 g_mmi_res_thm_fe1_1_5_shadow_range_str[] = "FE1_1_5_SHADOW_RANGE";
static const U8 g_mmi_res_thm_fe1_1_5_shadow_transparency_str[] = "FE1_1_5_SHADOW_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe1_1_6_shadow_degree_str[] = "FE1_1_6_SHADOW_DEGREE";
static const U8 g_mmi_res_thm_fe1_1_6_shadow_distant_str[] = "FE1_1_6_SHADOW_DISTANT";
static const U8 g_mmi_res_thm_fe1_1_6_shadow_range_str[] = "FE1_1_6_SHADOW_RANGE";
static const U8 g_mmi_res_thm_fe1_1_6_shadow_transparency_str[] = "FE1_1_6_SHADOW_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe1_1_7_shadow_degree_str[] = "FE1_1_7_SHADOW_DEGREE";
static const U8 g_mmi_res_thm_fe1_1_7_shadow_distant_str[] = "FE1_1_7_SHADOW_DISTANT";
static const U8 g_mmi_res_thm_fe1_1_7_shadow_range_str[] = "FE1_1_7_SHADOW_RANGE";
static const U8 g_mmi_res_thm_fe1_1_7_shadow_transparency_str[] = "FE1_1_7_SHADOW_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe1_1_8_shadow_degree_str[] = "FE1_1_8_SHADOW_DEGREE";
static const U8 g_mmi_res_thm_fe1_1_8_shadow_distant_str[] = "FE1_1_8_SHADOW_DISTANT";
static const U8 g_mmi_res_thm_fe1_1_8_shadow_range_str[] = "FE1_1_8_SHADOW_RANGE";
static const U8 g_mmi_res_thm_fe1_1_8_shadow_transparency_str[] = "FE1_1_8_SHADOW_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe1_1_9_shadow_degree_str[] = "FE1_1_9_SHADOW_DEGREE";
static const U8 g_mmi_res_thm_fe1_1_9_shadow_distant_str[] = "FE1_1_9_SHADOW_DISTANT";
static const U8 g_mmi_res_thm_fe1_1_9_shadow_range_str[] = "FE1_1_9_SHADOW_RANGE";
static const U8 g_mmi_res_thm_fe1_1_9_shadow_transparency_str[] = "FE1_1_9_SHADOW_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe2_2_1_outer_glow_range_str[] = "FE2_2_1_OUTER_GLOW_RANGE";
static const U8 g_mmi_res_thm_fe2_2_2_outer_glow_transparency_str[] = "FE2_2_2_OUTER_GLOW_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe3_3_1_engraved_degree_str[] = "FE3_3_1_ENGRAVED_DEGREE";
static const U8 g_mmi_res_thm_fe3_3_2_engraved_transparency_str[] = "FE3_3_2_ENGRAVED_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe4_4_1_gradient_direction_str[] = "FE4_4_1_GRADIENT_DIRECTION";
static const U8 g_mmi_res_thm_fe4_4_2_gradient_transparency_str[] = "FE4_4_2_GRADIENT_TRANSPARENCY";
static const U8 g_mmi_res_thm_fe5_5_1_border_size_str[] = "FE5_5_1_BORDER_SIZE";
static const U8 g_mmi_res_thm_fe5_5_2_border_transparency_str[] = "FE5_5_2_BORDER_TRANSPARENCY";

static const mmi_res_thm_id_str_tbl_struct g_mmi_res_thm_img_id_str_tbl[] =
{
	{0, 0, NULL},
};

static const mmi_res_thm_id_str_tbl_struct g_mmi_res_thm_col_id_str_tbl[] =
{
	{228, 29886, g_mmi_res_thm_fe1_1_1_shadow_color_str},
	{229, 29887, g_mmi_res_thm_fe1_1_2_shadow_color_str},
	{230, 29888, g_mmi_res_thm_fe1_1_3_shadow_color_str},
	{231, 29889, g_mmi_res_thm_fe1_1_4_shadow_color_str},
	{232, 29890, g_mmi_res_thm_fe1_1_5_shadow_color_str},
	{233, 29891, g_mmi_res_thm_fe1_1_6_shadow_color_str},
	{234, 29892, g_mmi_res_thm_fe1_1_7_shadow_color_str},
	{235, 29893, g_mmi_res_thm_fe1_1_8_shadow_color_str},
	{236, 29894, g_mmi_res_thm_fe1_1_9_shadow_color_str},
	{75, 29895, g_mmi_res_thm_fe2_2_3_outer_glow_color_str},
	{94, 29896, g_mmi_res_thm_fe3_3_3_upper_engraved_color_str},
	{92, 29897, g_mmi_res_thm_fe3_3_4_lower_engraved_color_str},
	{94, 29898, g_mmi_res_thm_fe4_4_3_first_gradient_color_str},
	{147, 29899, g_mmi_res_thm_fe4_4_4_second_gradient_color_str},
	{230, 29900, g_mmi_res_thm_fe5_5_3_border_color_str},
};

static const mmi_res_thm_id_str_tbl_struct g_mmi_res_thm_fnt_id_str_tbl[] =
{
	{0, 0, NULL},
};

static const mmi_res_thm_id_str_tbl_struct g_mmi_res_thm_int_id_str_tbl[] =
{
	{18, 29886, g_mmi_res_thm_fe1_1_1_shadow_degree_str},
	{125, 29887, g_mmi_res_thm_fe1_1_1_shadow_distant_str},
	{210, 29888, g_mmi_res_thm_fe1_1_1_shadow_range_str},
	{2, 29889, g_mmi_res_thm_fe1_1_1_shadow_transparency_str},
	{19, 29890, g_mmi_res_thm_fe1_1_2_shadow_degree_str},
	{126, 29891, g_mmi_res_thm_fe1_1_2_shadow_distant_str},
	{211, 29892, g_mmi_res_thm_fe1_1_2_shadow_range_str},
	{3, 29893, g_mmi_res_thm_fe1_1_2_shadow_transparency_str},
	{20, 29894, g_mmi_res_thm_fe1_1_3_shadow_degree_str},
	{127, 29895, g_mmi_res_thm_fe1_1_3_shadow_distant_str},
	{212, 29896, g_mmi_res_thm_fe1_1_3_shadow_range_str},
	{4, 29897, g_mmi_res_thm_fe1_1_3_shadow_transparency_str},
	{21, 29898, g_mmi_res_thm_fe1_1_4_shadow_degree_str},
	{128, 29899, g_mmi_res_thm_fe1_1_4_shadow_distant_str},
	{213, 29900, g_mmi_res_thm_fe1_1_4_shadow_range_str},
	{5, 29901, g_mmi_res_thm_fe1_1_4_shadow_transparency_str},
	{22, 29902, g_mmi_res_thm_fe1_1_5_shadow_degree_str},
	{129, 29903, g_mmi_res_thm_fe1_1_5_shadow_distant_str},
	{214, 29904, g_mmi_res_thm_fe1_1_5_shadow_range_str},
	{6, 29905, g_mmi_res_thm_fe1_1_5_shadow_transparency_str},
	{23, 29906, g_mmi_res_thm_fe1_1_6_shadow_degree_str},
	{130, 29907, g_mmi_res_thm_fe1_1_6_shadow_distant_str},
	{215, 29908, g_mmi_res_thm_fe1_1_6_shadow_range_str},
	{7, 29909, g_mmi_res_thm_fe1_1_6_shadow_transparency_str},
	{24, 29910, g_mmi_res_thm_fe1_1_7_shadow_degree_str},
	{131, 29911, g_mmi_res_thm_fe1_1_7_shadow_distant_str},
	{216, 29912, g_mmi_res_thm_fe1_1_7_shadow_range_str},
	{8, 29913, g_mmi_res_thm_fe1_1_7_shadow_transparency_str},
	{25, 29914, g_mmi_res_thm_fe1_1_8_shadow_degree_str},
	{132, 29915, g_mmi_res_thm_fe1_1_8_shadow_distant_str},
	{217, 29916, g_mmi_res_thm_fe1_1_8_shadow_range_str},
	{9, 29917, g_mmi_res_thm_fe1_1_8_shadow_transparency_str},
	{26, 29918, g_mmi_res_thm_fe1_1_9_shadow_degree_str},
	{133, 29919, g_mmi_res_thm_fe1_1_9_shadow_distant_str},
	{218, 29920, g_mmi_res_thm_fe1_1_9_shadow_range_str},
	{10, 29921, g_mmi_res_thm_fe1_1_9_shadow_transparency_str},
	{55, 29922, g_mmi_res_thm_fe2_2_1_outer_glow_range_str},
	{103, 29923, g_mmi_res_thm_fe2_2_2_outer_glow_transparency_str},
	{156, 29924, g_mmi_res_thm_fe3_3_1_engraved_degree_str},
	{141, 29925, g_mmi_res_thm_fe3_3_2_engraved_transparency_str},
	{150, 29926, g_mmi_res_thm_fe4_4_1_gradient_direction_str},
	{145, 29927, g_mmi_res_thm_fe4_4_2_gradient_transparency_str},
	{160, 29928, g_mmi_res_thm_fe5_5_1_border_size_str},
	{3, 29929, g_mmi_res_thm_fe5_5_2_border_transparency_str},
};

static const mmi_res_thm_id_str_tbl_struct g_mmi_res_thm_ado_id_str_tbl[] =
{
	{0, 0, NULL},
};

static const mmi_res_thm_id_str_tbl_struct g_mmi_res_thm_bin_id_str_tbl[] =
{
	{0, 0, NULL},
};

#endif /* __CUST_VENUS_THEME_ID_H__ */