/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_cache_table.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   03 13 2011 yan.liang
 *
 *******************************************************************************/
/********************************************************
 *  This file is generated automatically by resource gen
 *  Please do not modify it here manually 
 ***********************************************************/
#include "common_nvram_editor_data_item.h"
#define MMI_CACHE_BYTE_NUMBER 94
#define MMI_CACHE_SHORT_NUMBER 25
#define MMI_CACHE_DOUBLE_NUMBER 30


kal_uint16 mmi_rp_mmi_cache_get_byte_number(void)
{
    return MMI_CACHE_BYTE_NUMBER;
}
kal_uint16 mmi_rp_mmi_cache_get_short_number(void)
{
    return MMI_CACHE_SHORT_NUMBER;
}
kal_uint16 mmi_rp_mmi_cache_get_double_number(void)
{
    return MMI_CACHE_DOUBLE_NUMBER;
}


const kal_uint16 MMI_CACHE_BYTE_ENUM_TABLE[MMI_CACHE_BYTE_NUMBER] =
{
    23600,   /* 0 -- NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
     9578,   /* 1 -- NVRAM_CALLSET_FLIP_TO_MUTE_CALL */
    33612,   /* 2 -- NVRAM_WC_DST */
    24502,   /* 3 -- NVRAM_SETTING_LANG */
    23623,   /* 4 -- NVRAM_SETTING_PICTURE_QUALITY */
     9468,   /* 5 -- NVRAM_SMS_MISCELL_SETTING */
    24601,   /* 6 -- GPS_TIME_SYNC_MODE */
    23472,   /* 7 -- NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
     4811,   /* 8 -- NVRAM_MRE_SRV_DA_IS_WIFI_ONLY */
    30589,   /* 9 -- NVRAM_BT_POWER_STATUS */
    29387,   /* 10 -- NVRAM_PHB_SAVE_CONTACT_NOTIFY */
    23656,   /* 11 -- NVRAM_NETSET_3G_CAPACITY_SIM */
    31535,   /* 12 -- NVRAM_IMGVIEW_VIEW_SYTLE */
    35972,   /* 13 -- NVRAM_PHNSET_LIVE_WALLPAPER */
    25628,   /* 14 -- NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
    33608,   /* 15 -- CURRENT_CITY */
    23471,   /* 16 -- NVRAM_IME_AUTO_COMPLETION_FLAG */
    23485,   /* 17 -- NVRAM_SETTING_HANDWRITING_ON */
    11877,   /* 18 -- NVRAM_EF_FMGR_SORT_OPTION_LID */
    35971,   /* 19 -- NVRAM_WALLPAPER_ROTATE_STATUS */
    29388,   /* 20 -- NVRAM_SSC_DISABLE_FLAG */
    27497,   /* 21 -- NVRAM_REMINDER_TURNOVER_SENSOR_STATE */
    29390,   /* 22 -- NVRAM_SETTING_SPEED_DIAL */
    37197,   /* 23 -- RESTORE_DEFAULT_OWNER_NO */
     9575,   /* 24 -- NVRAM_CALLSET_QUICK_END_FLAG */
    23597,   /* 25 -- NVRAM_BYTE_LED_SETTING */
    29378,   /* 26 -- NVRAM_PHB_SPEAK_NAME_ON_OFF */
    23487,   /* 27 -- NVRAM_SETTING_STROKE_COLOR_INDEX */
    31878,   /* 28 -- NVRAM_AUDPLY_SINGLE_VOL */
     9574,   /* 29 -- NVRAM_CALLSET_REDIAL */
     7608,   /* 30 -- NVRAM_GPS_PAYLOAD_STORAGE */
    29383,   /* 31 -- NVRAM_PHB_NAME_DISPLAY_TYPE */
     9573,   /* 32 -- NVRAM_CALLSET_CALL_TIME_DISPLAY */
     9467,   /* 33 -- NVRAM_SMS_ACTIVE_PROFILE_INDEX */
    27550,   /* 34 -- NVRAM_SRV_SNDREC_QUALITY */
    33609,   /* 35 -- FOREIGN_CITY */
    24497,   /* 36 -- TIME_FORMAT */
    24499,   /* 37 -- RESTORE_DEFAULT_TIME_FORMAT */
    33610,   /* 38 -- NVRAM_SETTING_DT_DST */
    23601,   /* 39 -- NVRAM_BYTE_COVER_CLOSE_REJECT_CALL */
    39345,   /* 40 -- RESTORE_DEFAULT_AUTOUPDATE_TIME */
    23483,   /* 41 -- NVRAM_SETTING_PEN_SPEED */
    23486,   /* 42 -- NVRAM_SETTING_PEN_WIDTH */
    23655,   /* 43 -- NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
    29389,   /* 44 -- NVRAM_IDLE_DIALER_SEARCH_SETTING */
    37202,   /* 45 -- NVRAM_PHNSET_MAIN_MENU_STYLE */
    23593,   /* 46 -- NVRAM_SETTING_CONTRAST_SUBLCD_LEVEL */
    24498,   /* 47 -- DATE_FORMAT */
    24500,   /* 48 -- RESTORE_DEFAULT_DATE_FORMAT */
     7607,   /* 49 -- NRRAM_GPS_LOGGING_SWITCH */
    29380,   /* 50 -- NVRAM_PHB_STARTUP_COPY_SIM2 */
    29381,   /* 51 -- NVRAM_PHB_STARTUP_COPY_SIM3 */
    29382,   /* 52 -- NVRAM_PHB_STARTUP_COPY_SIM4 */
    23477,   /* 53 -- NVRAM_IME_INPUT_PATTERN */
     9579,   /* 54 -- NVRAM_CALLSET_TAP_TAP_TO_RECORD_IN_CALL */
    29379,   /* 55 -- NVRAM_PHB_STARTUP_COPY_SIM */
    37200,   /* 56 -- NVRAM_UPDATE_DATETIME_MODE */
     7765,   /* 57 -- NVRAM_PROFILES_LASTACTIVATED */
    23484,   /* 58 -- NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
    23598,   /* 59 -- NVRAM_BYTE_BL_SETTING_LEVEL */
    37196,   /* 60 -- NVRAM_SETTING_OWNER_NO */
     9571,   /* 61 -- NVRAM_CALLSET_CTR_MODE */
    33614,   /* 62 -- NVRAM_DOWNLOAD_CITY1 */
    33615,   /* 63 -- NVRAM_DOWNLOAD_CITY2 */
    12686,   /* 64 -- NVRAM_DEFAULT_USB_APP */
    27475,   /* 65 -- NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
    23469,   /* 66 -- NVRAM_IME_SMART_MODE_CONFIG */
    24501,   /* 67 -- NVRAM_DT_SEP_FORMAT */
    15533,   /* 68 -- BT_BQB_TEST */
    23592,   /* 69 -- NVRAM_SETTING_CONTRAST_LEVEL */
    23475,   /* 70 -- NVRAM_IME_VIBRATION_FLAG */
    23473,   /* 71 -- NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
    27549,   /* 72 -- NVRAM_SRV_SNDREC_STORAGE */
    24455,   /* 73 -- NVRAM_DUALMODE_MODE_SWITCH_TYPE */
    23476,   /* 74 -- NVRAM_IME_SOUND_FEEDBACK_FLAG */
    23654,   /* 75 -- NVRAM_NETSET_PREFERRED_MODE */
    23596,   /* 76 -- NVRAM_HDSET_MODE_VOICE_LEVEL */
    30587,   /* 77 -- NVRAM_BT_RECEIVE_DRIVE */
    27551,   /* 78 -- NVRAM_AUTO_VM_SETTING_AUTO_VM */
    23595,   /* 79 -- NVRAM_LDSPK_MODE_VOICE_LEVEL */
    30588,   /* 80 -- NVRAM_BT_RECEIVE_DRIVE_ASK */
    25627,   /* 81 -- NVRAM_SETTING_AUTOKEYPADLOCK */
    23594,   /* 82 -- NVRAM_NORMAL_MODE_VOICE_LEVEL */
    24602,   /* 83 -- SRV_DT_TIME_ZONE */
    37198,   /* 84 -- NVRAM_SETTING_STATUS_DT_TIME */
     7764,   /* 85 -- NVRAM_PROFILES_ACTIVATED */
    23470,   /* 86 -- NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
    23474,   /* 87 -- NVRAM_IME_AUTO_SPACE_FLAG */
    29564,   /* 88 -- NVRAM_SETTING_AUTOUPDATE_DT_TIME_STATUS */
    30200,   /* 89 -- NVRAM_ADUPS_SETTING_LID */
    23602,   /* 90 -- NVRAM_BYTE_COVER_CLOSE_KEYPAD_LOCK */
    37199,   /* 91 -- NVRAM_AUTOUPDATE_DT_STATUS */
    25658,   /* 92 -- NVRAM_IDLE_DIALER_TTS_SETTING */
     9572,   /* 93 -- NVRAM_CALLSET_ANSWER_MODE */
};

const kal_uint16 MMI_CACHE_SHORT_ENUM_TABLE[MMI_CACHE_SHORT_NUMBER] =
{
    23478,   /* 0 -- NVRAM_SETTING_PREFER_INPUT_METHOD */
     9469,   /* 1 -- NVRAM_SMS_CONCAT_MSG_REF_VALUE */
    36172,   /* 2 -- NVRAM_CURRENT_POWER_OFF_DISPLAY */
    23480,   /* 3 -- NVRAM_SETTING_WRITING_LANG */
    36171,   /* 4 -- NVRAM_CURRENT_POWER_ON_DISPLAY */
     9577,   /* 5 -- NVRAM_CALLSET_QUICK_END_TIME */
    29384,   /* 6 -- NVRAM_PHB_STORAGE_LOCATION */
    33613,   /* 7 -- NVRAM_FRN_TIMEZONE */
    23479,   /* 8 -- RESTORE_PREFER_INPUT_METHOD */
    35976,   /* 9 -- RESTORE_DEFAULT_SETWALLPAPER_SUB */
    23599,   /* 10 -- NVRAM_BYTE_BL_SETTING_HFTIME */
    29386,   /* 11 -- NVRAM_PHB_VCARD_VERSION */
    23482,   /* 12 -- NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
    36170,   /* 13 -- NVRAM_RESTORE_POWER_OFF_DISPLAY */
    29385,   /* 14 -- NVRAM_PHB_NAME_LIST_FILTER */
    31038,   /* 15 -- NVRAM_POWER_ON_DISPLAY_SUCCESS */
     9576,   /* 16 -- NVRAM_CALLSET_CTR_TIME */
    35974,   /* 17 -- RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER */
    33611,   /* 18 -- NVRAM_TIMEZONE */
    36169,   /* 19 -- NVRAM_RESTORE_POWER_ON_DISPLAY */
    23481,   /* 20 -- NVRAM_SETTING_WRITING_LANG_SUB */
    31536,   /* 21 -- NVRAM_IMGVIEW_STORAGE */
    29391,   /* 22 -- NVRAM_PHB_PBAPC_NAME_ORDER */
    35973,   /* 23 -- NVRAM_FUNANDGAMES_SETWALLPAPER */
    35975,   /* 24 -- NVRAM_SETWALLPAPER_SUB */
};

const kal_uint16 MMI_CACHE_DOUBLE_ENUM_TABLE[MMI_CACHE_DOUBLE_NUMBER] =
{
    37201,   /* 0 -- NVRAM_RTC_TIME */
    35970,   /* 1 -- NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
    24466,   /* 2 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1 */
    24467,   /* 3 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2 */
    24468,   /* 4 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3 */
    24469,   /* 5 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4 */
    24470,   /* 6 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5 */
    24471,   /* 7 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6 */
    24472,   /* 8 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7 */
    24473,   /* 9 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8 */
    35968,   /* 10 -- NARAM_DISPCHAR_AVATAR_ONOFF */
     4803,   /* 11 -- NVRAM_MRE_SRV_DA_SIM1 */
     4805,   /* 12 -- NVRAM_MRE_SRV_DA_SIM2 */
     4807,   /* 13 -- NVRAM_MRE_SRV_DA_SIM3 */
     4809,   /* 14 -- NVRAM_MRE_SRV_DA_SIM4 */
    35967,   /* 15 -- NVRAM_DISPCHAR_AVATAR_WPSS */
     7766,   /* 16 -- NVRAM_SRV_PROF_EXT_MELODY_BITS */
    24474,   /* 17 -- NVRAM_PEN_CALIBRATION_VALUE1 */
    24475,   /* 18 -- NVRAM_PEN_CALIBRATION_VALUE2 */
    24476,   /* 19 -- NVRAM_PEN_CALIBRATION_VALUE3 */
    24477,   /* 20 -- NVRAM_PEN_CALIBRATION_VALUE4 */
    24478,   /* 21 -- NVRAM_PEN_CALIBRATION_VALUE5 */
    24479,   /* 22 -- NVRAM_PEN_CALIBRATION_VALUE6 */
    24480,   /* 23 -- NVRAM_PEN_CALIBRATION_VALUE7 */
    24481,   /* 24 -- NVRAM_PEN_CALIBRATION_VALUE8 */
    35969,   /* 25 -- NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
     4804,   /* 26 -- NVRAM_MRE_SRV_DA_SIM1_PX */
     4806,   /* 27 -- NVRAM_MRE_SRV_DA_SIM2_PX */
     4808,   /* 28 -- NVRAM_MRE_SRV_DA_SIM3_PX */
     4810,   /* 29 -- NVRAM_MRE_SRV_DA_SIM4_PX */
};



const kal_uint32 NVRAM_EF_MMI_CACHE_BYTE_KEY_DEFAULT[NVRAM_MMI_CACHE_BYTE_KEY_SIZE * NVRAM_MMI_CACHE_BYTE_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x0033E086,   /* 0 -- NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
    0x0477B0F7,   /* 1 -- NVRAM_CALLSET_FLIP_TO_MUTE_CALL */
    0x0588B0F2,   /* 2 -- NVRAM_WC_DST */
    0x0C5FC9DD,   /* 3 -- NVRAM_SETTING_LANG */
    0x1047E32F,   /* 4 -- NVRAM_SETTING_PICTURE_QUALITY */
    0x10FD69C4,   /* 5 -- NVRAM_SMS_MISCELL_SETTING */
    0x13774D01,   /* 6 -- GPS_TIME_SYNC_MODE */
    0x14915C3B,   /* 7 -- NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
    0x14F6111C,   /* 8 -- NVRAM_MRE_SRV_DA_IS_WIFI_ONLY */
    0x15654019,   /* 9 -- NVRAM_BT_POWER_STATUS */
    0x19F031B5,   /* 10 -- NVRAM_PHB_SAVE_CONTACT_NOTIFY */
    0x21246C43,   /* 11 -- NVRAM_NETSET_3G_CAPACITY_SIM */
    0x2322B5A4,   /* 12 -- NVRAM_IMGVIEW_VIEW_SYTLE */
    0x25031C82,   /* 13 -- NVRAM_PHNSET_LIVE_WALLPAPER */
    0x2A9FDCAF,   /* 14 -- NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
    0x2E994CA8,   /* 15 -- CURRENT_CITY */
    0x338FF87D,   /* 16 -- NVRAM_IME_AUTO_COMPLETION_FLAG */
    0x33E27B20,   /* 17 -- NVRAM_SETTING_HANDWRITING_ON */
    0x33E2BC2F,   /* 18 -- NVRAM_EF_FMGR_SORT_OPTION_LID */
    0x3617F479,   /* 19 -- NVRAM_WALLPAPER_ROTATE_STATUS */
    0x3911329F,   /* 20 -- NVRAM_SSC_DISABLE_FLAG */
    0x3DFB058D,   /* 21 -- NVRAM_REMINDER_TURNOVER_SENSOR_STATE */
    0x3F180537,   /* 22 -- NVRAM_SETTING_SPEED_DIAL */
    0x410A8A93,   /* 23 -- RESTORE_DEFAULT_OWNER_NO */
    0x4214065D,   /* 24 -- NVRAM_CALLSET_QUICK_END_FLAG */
    0x455E5A65,   /* 25 -- NVRAM_BYTE_LED_SETTING */
    0x4AC1FB21,   /* 26 -- NVRAM_PHB_SPEAK_NAME_ON_OFF */
    0x5A4072DE,   /* 27 -- NVRAM_SETTING_STROKE_COLOR_INDEX */
    0x5C355B2E,   /* 28 -- NVRAM_AUDPLY_SINGLE_VOL */
    0x5C5012DE,   /* 29 -- NVRAM_CALLSET_REDIAL */
    0x5EA03F95,   /* 30 -- NVRAM_GPS_PAYLOAD_STORAGE */
    0x605F66F6,   /* 31 -- NVRAM_PHB_NAME_DISPLAY_TYPE */
    0x613F6FD6,   /* 32 -- NVRAM_CALLSET_CALL_TIME_DISPLAY */
    0x61D48B89,   /* 33 -- NVRAM_SMS_ACTIVE_PROFILE_INDEX */
    0x62CC3DCF,   /* 34 -- NVRAM_SRV_SNDREC_QUALITY */
    0x63D46A2D,   /* 35 -- FOREIGN_CITY */
    0x655C92B2,   /* 36 -- TIME_FORMAT */
    0x66FB6043,   /* 37 -- RESTORE_DEFAULT_TIME_FORMAT */
    0x670179A5,   /* 38 -- NVRAM_SETTING_DT_DST */
    0x694DA578,   /* 39 -- NVRAM_BYTE_COVER_CLOSE_REJECT_CALL */
    0x6A89B90E,   /* 40 -- RESTORE_DEFAULT_AUTOUPDATE_TIME */
    0x6C769ED2,   /* 41 -- NVRAM_SETTING_PEN_SPEED */
    0x6CABCC51,   /* 42 -- NVRAM_SETTING_PEN_WIDTH */
    0x747C6326,   /* 43 -- NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
    0x796DC810,   /* 44 -- NVRAM_IDLE_DIALER_SEARCH_SETTING */
    0x7B8B4124,   /* 45 -- NVRAM_PHNSET_MAIN_MENU_STYLE */
    0x7E232E40,   /* 46 -- NVRAM_SETTING_CONTRAST_SUBLCD_LEVEL */
    0x82A4E6B1,   /* 47 -- DATE_FORMAT */
    0x8443B442,   /* 48 -- RESTORE_DEFAULT_DATE_FORMAT */
    0x85365EC5,   /* 49 -- NRRAM_GPS_LOGGING_SWITCH */
    0x8602068E,   /* 50 -- NVRAM_PHB_STARTUP_COPY_SIM2 */
    0x8602068F,   /* 51 -- NVRAM_PHB_STARTUP_COPY_SIM3 */
    0x86020690,   /* 52 -- NVRAM_PHB_STARTUP_COPY_SIM4 */
    0x88D6787D,   /* 53 -- NVRAM_IME_INPUT_PATTERN */
    0x8905997B,   /* 54 -- NVRAM_CALLSET_TAP_TAP_TO_RECORD_IN_CALL */
    0x90B5BE24,   /* 55 -- NVRAM_PHB_STARTUP_COPY_SIM */
    0x91CCA231,   /* 56 -- NVRAM_UPDATE_DATETIME_MODE */
    0x9F895786,   /* 57 -- NVRAM_PROFILES_LASTACTIVATED */
    0x9FC8B78B,   /* 58 -- NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
    0xA08D6C77,   /* 59 -- NVRAM_BYTE_BL_SETTING_LEVEL */
    0xA4F4B75C,   /* 60 -- NVRAM_SETTING_OWNER_NO */
    0xA502111C,   /* 61 -- NVRAM_CALLSET_CTR_MODE */
    0xB084A4EF,   /* 62 -- NVRAM_DOWNLOAD_CITY1 */
    0xB084A4F0,   /* 63 -- NVRAM_DOWNLOAD_CITY2 */
    0xB1A07148,   /* 64 -- NVRAM_DEFAULT_USB_APP */
    0xB3C62531,   /* 65 -- NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
    0xB4319F6A,   /* 66 -- NVRAM_IME_SMART_MODE_CONFIG */
    0xB4ADFEE7,   /* 67 -- NVRAM_DT_SEP_FORMAT */
    0xB713C9D4,   /* 68 -- BT_BQB_TEST */
    0xBA41A116,   /* 69 -- NVRAM_SETTING_CONTRAST_LEVEL */
    0xBAB0B4B7,   /* 70 -- NVRAM_IME_VIBRATION_FLAG */
    0xCA6F0937,   /* 71 -- NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
    0xCBABBF4B,   /* 72 -- NVRAM_SRV_SNDREC_STORAGE */
    0xD4572DA9,   /* 73 -- NVRAM_DUALMODE_MODE_SWITCH_TYPE */
    0xD4BAD7B8,   /* 74 -- NVRAM_IME_SOUND_FEEDBACK_FLAG */
    0xD523D15B,   /* 75 -- NVRAM_NETSET_PREFERRED_MODE */
    0xD598E1F4,   /* 76 -- NVRAM_HDSET_MODE_VOICE_LEVEL */
    0xD67F2B01,   /* 77 -- NVRAM_BT_RECEIVE_DRIVE */
    0xDC4F3C00,   /* 78 -- NVRAM_AUTO_VM_SETTING_AUTO_VM */
    0xDCE10CA4,   /* 79 -- NVRAM_LDSPK_MODE_VOICE_LEVEL */
    0xDD2BF01B,   /* 80 -- NVRAM_BT_RECEIVE_DRIVE_ASK */
    0xDE69511D,   /* 81 -- NVRAM_SETTING_AUTOKEYPADLOCK */
    0xDEED7E73,   /* 82 -- NVRAM_NORMAL_MODE_VOICE_LEVEL */
    0xE1A466EE,   /* 83 -- SRV_DT_TIME_ZONE */
    0xE4CB8EFE,   /* 84 -- NVRAM_SETTING_STATUS_DT_TIME */
    0xE639E6DC,   /* 85 -- NVRAM_PROFILES_ACTIVATED */
    0xE928235D,   /* 86 -- NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
    0xEE1A67D7,   /* 87 -- NVRAM_IME_AUTO_SPACE_FLAG */
    0xEE6763CD,   /* 88 -- NVRAM_SETTING_AUTOUPDATE_DT_TIME_STATUS */
    0xF1A42D6E,   /* 89 -- NVRAM_ADUPS_SETTING_LID */
    0xF8A67B30,   /* 90 -- NVRAM_BYTE_COVER_CLOSE_KEYPAD_LOCK */
    0xFA0E117A,   /* 91 -- NVRAM_AUTOUPDATE_DT_STATUS */
    0xFC2179AD,   /* 92 -- NVRAM_IDLE_DIALER_TTS_SETTING */
    0xFCAC03A9,   /* 93 -- NVRAM_CALLSET_ANSWER_MODE */
};

const kal_uint32 NVRAM_EF_MMI_CACHE_SHORT_KEY_DEFAULT[NVRAM_MMI_CACHE_SHORT_KEY_SIZE * NVRAM_MMI_CACHE_SHORT_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x0C2C7116,   /* 0 -- NVRAM_SETTING_PREFER_INPUT_METHOD */
    0x1D98ABC2,   /* 1 -- NVRAM_SMS_CONCAT_MSG_REF_VALUE */
    0x238E70B2,   /* 2 -- NVRAM_CURRENT_POWER_OFF_DISPLAY */
    0x2D593480,   /* 3 -- NVRAM_SETTING_WRITING_LANG */
    0x3D11F342,   /* 4 -- NVRAM_CURRENT_POWER_ON_DISPLAY */
    0x421A59BE,   /* 5 -- NVRAM_CALLSET_QUICK_END_TIME */
    0x446216AE,   /* 6 -- NVRAM_PHB_STORAGE_LOCATION */
    0x54329DD6,   /* 7 -- NVRAM_FRN_TIMEZONE */
    0x55C9E89D,   /* 8 -- RESTORE_PREFER_INPUT_METHOD */
    0x61E906E7,   /* 9 -- RESTORE_DEFAULT_SETWALLPAPER_SUB */
    0x6A59FE18,   /* 10 -- NVRAM_BYTE_BL_SETTING_HFTIME */
    0x79A7A46A,   /* 11 -- NVRAM_PHB_VCARD_VERSION */
    0x84CB0748,   /* 12 -- NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
    0x890C4A87,   /* 13 -- NVRAM_RESTORE_POWER_OFF_DISPLAY */
    0x910F4C1A,   /* 14 -- NVRAM_PHB_NAME_LIST_FILTER */
    0xA203F3C0,   /* 15 -- NVRAM_POWER_ON_DISPLAY_SUCCESS */
    0xA5052A46,   /* 16 -- NVRAM_CALLSET_CTR_TIME */
    0xA9842A5C,   /* 17 -- RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER */
    0xAD3C1B39,   /* 18 -- NVRAM_TIMEZONE */
    0xBC370ACD,   /* 19 -- NVRAM_RESTORE_POWER_ON_DISPLAY */
    0xBCD765E1,   /* 20 -- NVRAM_SETTING_WRITING_LANG_SUB */
    0xBE99E6A4,   /* 21 -- NVRAM_IMGVIEW_STORAGE */
    0xD9EACFAC,   /* 22 -- NVRAM_PHB_PBAPC_NAME_ORDER */
    0xDC2A15F6,   /* 23 -- NVRAM_FUNANDGAMES_SETWALLPAPER */
    0xEF592C81,   /* 24 -- NVRAM_SETWALLPAPER_SUB */
};

const kal_uint32 NVRAM_EF_MMI_CACHE_DOUBLE_KEY_DEFAULT[NVRAM_MMI_CACHE_DOUBLE_KEY_SIZE * NVRAM_MMI_CACHE_DOUBLE_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x13B9694B,   /* 0 -- NVRAM_RTC_TIME */
    0x29B4FC84,   /* 1 -- NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
    0x4C5F3D2A,   /* 2 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1 */
    0x4C5F3D2B,   /* 3 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2 */
    0x4C5F3D2C,   /* 4 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3 */
    0x4C5F3D2D,   /* 5 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4 */
    0x4C5F3D2E,   /* 6 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5 */
    0x4C5F3D2F,   /* 7 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6 */
    0x4C5F3D30,   /* 8 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7 */
    0x4C5F3D31,   /* 9 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8 */
    0x55D698C6,   /* 10 -- NARAM_DISPCHAR_AVATAR_ONOFF */
    0x62F30CB5,   /* 11 -- NVRAM_MRE_SRV_DA_SIM1 */
    0x62F30CB6,   /* 12 -- NVRAM_MRE_SRV_DA_SIM2 */
    0x62F30CB7,   /* 13 -- NVRAM_MRE_SRV_DA_SIM3 */
    0x62F30CB8,   /* 14 -- NVRAM_MRE_SRV_DA_SIM4 */
    0x98AE5398,   /* 15 -- NVRAM_DISPCHAR_AVATAR_WPSS */
    0xB68B1B79,   /* 16 -- NVRAM_SRV_PROF_EXT_MELODY_BITS */
    0xC384715B,   /* 17 -- NVRAM_PEN_CALIBRATION_VALUE1 */
    0xC384715C,   /* 18 -- NVRAM_PEN_CALIBRATION_VALUE2 */
    0xC384715D,   /* 19 -- NVRAM_PEN_CALIBRATION_VALUE3 */
    0xC384715E,   /* 20 -- NVRAM_PEN_CALIBRATION_VALUE4 */
    0xC384715F,   /* 21 -- NVRAM_PEN_CALIBRATION_VALUE5 */
    0xC3847160,   /* 22 -- NVRAM_PEN_CALIBRATION_VALUE6 */
    0xC3847161,   /* 23 -- NVRAM_PEN_CALIBRATION_VALUE7 */
    0xC3847162,   /* 24 -- NVRAM_PEN_CALIBRATION_VALUE8 */
    0xD017390B,   /* 25 -- NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
    0xD9F529D2,   /* 26 -- NVRAM_MRE_SRV_DA_SIM1_PX */
    0xD9F59E31,   /* 27 -- NVRAM_MRE_SRV_DA_SIM2_PX */
    0xD9F61290,   /* 28 -- NVRAM_MRE_SRV_DA_SIM3_PX */
    0xD9F686EF,   /* 29 -- NVRAM_MRE_SRV_DA_SIM4_PX */
};



#ifdef __MTK_INTERNAL__
/* type (1: byte cache,  2: short cache   8:double cache) */
/* This API is only used for meta tool */
kal_int16 mmi_rp_mmi_cache_search_index(kal_uint16 nDataItemId, kal_uint8 nDataType)
{
    kal_uint16 index, total= 0;
    const kal_uint16 *tbl;

    switch(nDataType)
    {
    case 1:
        tbl = MMI_CACHE_BYTE_ENUM_TABLE;
        total = MMI_CACHE_BYTE_NUMBER;
        break;
    case 2:
        tbl = MMI_CACHE_SHORT_ENUM_TABLE;
        total = MMI_CACHE_SHORT_NUMBER;
        break;
    case 8:
        tbl = MMI_CACHE_DOUBLE_ENUM_TABLE;
        total = MMI_CACHE_DOUBLE_NUMBER;
        break;
    default:
        tbl = NULL;
        total = 0;
    }
    for( index = 0 ; index < total ; index++)
    {
        if (tbl[index] == nDataItemId)
            return index;
    }
    return -1;
}
#endif


/********************************************************
 *  This file is generated automatically by resource gen
 *  Please do not modify it here manually 
 ***********************************************************/



#include "mmi_res_range_def.h"
#include "nvram_enums.h"
#include "nvram_interface.h"



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_byte_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_byte to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_byte_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
	 nvram_get_default_value(NVRAM_EF_CACHE_BYTE_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BLUETOOTH: 
        buffer[ 77] = def_buf[ 77];     /* 30587: NVRAM_BT_RECEIVE_DRIVE */
        buffer[ 80] = def_buf[ 80];     /* 30588: NVRAM_BT_RECEIVE_DRIVE_ASK */
        buffer[  9] = def_buf[  9];     /* 30589: NVRAM_BT_POWER_STATUS */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        buffer[ 12] = def_buf[ 12];     /* 31535: NVRAM_IMGVIEW_VIEW_SYTLE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        buffer[ 28] = def_buf[ 28];     /* 31878: NVRAM_AUDPLY_SINGLE_VOL */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        buffer[ 15] = def_buf[ 15];     /* 33608: CURRENT_CITY */
        buffer[ 35] = def_buf[ 35];     /* 33609: FOREIGN_CITY */
        buffer[ 38] = def_buf[ 38];     /* 33610: NVRAM_SETTING_DT_DST */
        buffer[  2] = def_buf[  2];     /* 33612: NVRAM_WC_DST */
        buffer[ 62] = def_buf[ 62];     /* 33614: NVRAM_DOWNLOAD_CITY1 */
        buffer[ 63] = def_buf[ 63];     /* 33615: NVRAM_DOWNLOAD_CITY2 */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[ 19] = def_buf[ 19];     /* 35971: NVRAM_WALLPAPER_ROTATE_STATUS */
        buffer[ 13] = def_buf[ 13];     /* 35972: NVRAM_PHNSET_LIVE_WALLPAPER */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        buffer[ 60] = def_buf[ 23];     /* 37196: NVRAM_SETTING_OWNER_NO = 37197: RESTORE_DEFAULT_OWNER_NO*/
        buffer[ 84] = def_buf[ 84];     /* 37198: NVRAM_SETTING_STATUS_DT_TIME */
        buffer[ 91] = def_buf[ 91];     /* 37199: NVRAM_AUTOUPDATE_DT_STATUS */
        buffer[ 56] = def_buf[ 56];     /* 37200: NVRAM_UPDATE_DATETIME_MODE */
        buffer[ 45] = def_buf[ 45];     /* 37202: NVRAM_PHNSET_MAIN_MENU_STYLE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        buffer[ 85] = def_buf[ 85];     /*  7764: NVRAM_PROFILES_ACTIVATED */
        buffer[ 57] = def_buf[ 57];     /*  7765: NVRAM_PROFILES_LASTACTIVATED */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        buffer[  5] = def_buf[  5];     /*  9468: NVRAM_SMS_MISCELL_SETTING */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        buffer[ 66] = def_buf[ 66];     /* 23469: NVRAM_IME_SMART_MODE_CONFIG */
        buffer[ 86] = def_buf[ 86];     /* 23470: NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
        buffer[ 16] = def_buf[ 16];     /* 23471: NVRAM_IME_AUTO_COMPLETION_FLAG */
        buffer[  7] = def_buf[  7];     /* 23472: NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
        buffer[ 71] = def_buf[ 71];     /* 23473: NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
        buffer[ 87] = def_buf[ 87];     /* 23474: NVRAM_IME_AUTO_SPACE_FLAG */
        buffer[ 70] = def_buf[ 70];     /* 23475: NVRAM_IME_VIBRATION_FLAG */
        buffer[ 74] = def_buf[ 74];     /* 23476: NVRAM_IME_SOUND_FEEDBACK_FLAG */
        buffer[ 53] = def_buf[ 53];     /* 23477: NVRAM_IME_INPUT_PATTERN */
        buffer[ 41] = def_buf[ 41];     /* 23483: NVRAM_SETTING_PEN_SPEED */
        buffer[ 58] = def_buf[ 58];     /* 23484: NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
        buffer[ 17] = def_buf[ 17];     /* 23485: NVRAM_SETTING_HANDWRITING_ON */
        buffer[ 42] = def_buf[ 42];     /* 23486: NVRAM_SETTING_PEN_WIDTH */
        buffer[ 27] = def_buf[ 27];     /* 23487: NVRAM_SETTING_STROKE_COLOR_INDEX */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        buffer[ 18] = def_buf[ 18];     /* 11877: NVRAM_EF_FMGR_SORT_OPTION_LID */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MDI: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        buffer[ 69] = def_buf[ 69];     /* 23592: NVRAM_SETTING_CONTRAST_LEVEL */
        buffer[ 25] = def_buf[ 25];     /* 23597: NVRAM_BYTE_LED_SETTING */
        buffer[ 59] = def_buf[ 59];     /* 23598: NVRAM_BYTE_BL_SETTING_LEVEL */
        buffer[  0] = def_buf[  0];     /* 23600: NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        buffer[  4] = def_buf[  4];     /* 23623: NVRAM_SETTING_PICTURE_QUALITY */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_BTCM: 
        buffer[ 68] = def_buf[ 68];     /* 15533: BT_BQB_TEST */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        buffer[ 75] = def_buf[ 75];     /* 23654: NVRAM_NETSET_PREFERRED_MODE */
        buffer[ 43] = def_buf[ 43];     /* 23655: NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
        buffer[ 11] = def_buf[ 11];     /* 23656: NVRAM_NETSET_3G_CAPACITY_SIM */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        buffer[ 61] = def_buf[ 61];     /*  9571: NVRAM_CALLSET_CTR_MODE */
        buffer[ 93] = def_buf[ 93];     /*  9572: NVRAM_CALLSET_ANSWER_MODE */
        buffer[ 32] = def_buf[ 32];     /*  9573: NVRAM_CALLSET_CALL_TIME_DISPLAY */
        buffer[ 29] = def_buf[ 29];     /*  9574: NVRAM_CALLSET_REDIAL */
        buffer[ 24] = def_buf[ 24];     /*  9575: NVRAM_CALLSET_QUICK_END_FLAG */
        buffer[  1] = def_buf[  1];     /*  9578: NVRAM_CALLSET_FLIP_TO_MUTE_CALL */
        buffer[ 54] = def_buf[ 54];     /*  9579: NVRAM_CALLSET_TAP_TAP_TO_RECORD_IN_CALL */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        buffer[ 73] = def_buf[ 73];     /* 24455: NVRAM_DUALMODE_MODE_SWITCH_TYPE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        buffer[ 36] = def_buf[ 36];     /* 24497: TIME_FORMAT */
        buffer[ 47] = def_buf[ 47];     /* 24498: DATE_FORMAT */
        buffer[ 67] = def_buf[ 67];     /* 24501: NVRAM_DT_SEP_FORMAT */
        buffer[  3] = def_buf[  3];     /* 24502: NVRAM_SETTING_LANG */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_DATETIME_SETTING: 
        buffer[  6] = def_buf[  6];     /* 24601: GPS_TIME_SYNC_MODE */
        buffer[ 83] = def_buf[ 83];     /* 24602: SRV_DT_TIME_ZONE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        buffer[ 92] = def_buf[ 92];     /* 25658: NVRAM_IDLE_DIALER_TTS_SETTING */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        buffer[ 81] = def_buf[ 81];     /* 25627: NVRAM_SETTING_AUTOKEYPADLOCK */
        buffer[ 14] = def_buf[ 14];     /* 25628: NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        buffer[ 65] = def_buf[ 65];     /* 27475: NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_REMINDER: 
        buffer[ 21] = def_buf[ 21];     /* 27497: NVRAM_REMINDER_TURNOVER_SENSOR_STATE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        buffer[ 72] = def_buf[ 72];     /* 27549: NVRAM_SRV_SNDREC_STORAGE */
        buffer[ 34] = def_buf[ 34];     /* 27550: NVRAM_SRV_SNDREC_QUALITY */
        buffer[ 78] = def_buf[ 78];     /* 27551: NVRAM_AUTO_VM_SETTING_AUTO_VM */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        buffer[ 26] = def_buf[ 26];     /* 29378: NVRAM_PHB_SPEAK_NAME_ON_OFF */
        buffer[ 31] = def_buf[ 31];     /* 29383: NVRAM_PHB_NAME_DISPLAY_TYPE */
        buffer[ 10] = def_buf[ 10];     /* 29387: NVRAM_PHB_SAVE_CONTACT_NOTIFY */
        buffer[ 44] = def_buf[ 44];     /* 29389: NVRAM_IDLE_DIALER_SEARCH_SETTING */
        buffer[ 22] = def_buf[ 22];     /* 29390: NVRAM_SETTING_SPEED_DIAL */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NITZ: 
        buffer[ 88] = def_buf[ 88];     /* 29564: NVRAM_SETTING_AUTOUPDATE_DT_TIME_STATUS */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ADUPS: 
        buffer[ 89] = def_buf[ 89];     /* 30200: NVRAM_ADUPS_SETTING_LID */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_short_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_short to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_short_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
	 nvram_get_default_value(NVRAM_EF_CACHE_SHORT_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BLUETOOTH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        buffer[ 42] = def_buf[ 42];     /* 31536: NVRAM_IMGVIEW_STORAGE */
        buffer[ 43] = def_buf[ 43];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        buffer[ 36] = def_buf[ 36];     /* 33611: NVRAM_TIMEZONE */
        buffer[ 37] = def_buf[ 37];
        buffer[ 14] = def_buf[ 14];     /* 33613: NVRAM_FRN_TIMEZONE */
        buffer[ 15] = def_buf[ 15];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[ 46] = def_buf[ 46];     /* 35973: NVRAM_FUNANDGAMES_SETWALLPAPER */
        buffer[ 47] = def_buf[ 47];
        buffer[ 48] = def_buf[ 18];     /* 35975: NVRAM_SETWALLPAPER_SUB = 35976: RESTORE_DEFAULT_SETWALLPAPER_SUB*/
        buffer[ 49] = def_buf[ 19];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        buffer[  8] = def_buf[ 38];     /* 36171: NVRAM_CURRENT_POWER_ON_DISPLAY = 36169: NVRAM_RESTORE_POWER_ON_DISPLAY*/
        buffer[  9] = def_buf[ 39];
        buffer[  4] = def_buf[ 26];     /* 36172: NVRAM_CURRENT_POWER_OFF_DISPLAY = 36170: NVRAM_RESTORE_POWER_OFF_DISPLAY*/
        buffer[  5] = def_buf[ 27];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        buffer[  0] = def_buf[ 16];     /* 23478: NVRAM_SETTING_PREFER_INPUT_METHOD = 23479: RESTORE_PREFER_INPUT_METHOD*/
        buffer[  1] = def_buf[ 17];
        buffer[  6] = def_buf[  6];     /* 23480: NVRAM_SETTING_WRITING_LANG */
        buffer[  7] = def_buf[  7];
        buffer[ 40] = def_buf[ 40];     /* 23481: NVRAM_SETTING_WRITING_LANG_SUB */
        buffer[ 41] = def_buf[ 41];
        buffer[ 24] = def_buf[ 24];     /* 23482: NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
        buffer[ 25] = def_buf[ 25];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MDI: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        buffer[ 20] = def_buf[ 20];     /* 23599: NVRAM_BYTE_BL_SETTING_HFTIME */
        buffer[ 21] = def_buf[ 21];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_BTCM: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        buffer[ 10] = def_buf[ 10];     /*  9577: NVRAM_CALLSET_QUICK_END_TIME */
        buffer[ 11] = def_buf[ 11];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_DATETIME_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_REMINDER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        buffer[ 12] = def_buf[ 12];     /* 29384: NVRAM_PHB_STORAGE_LOCATION */
        buffer[ 13] = def_buf[ 13];
        buffer[ 28] = def_buf[ 28];     /* 29385: NVRAM_PHB_NAME_LIST_FILTER */
        buffer[ 29] = def_buf[ 29];
        buffer[ 22] = def_buf[ 22];     /* 29386: NVRAM_PHB_VCARD_VERSION */
        buffer[ 23] = def_buf[ 23];
        buffer[ 44] = def_buf[ 44];     /* 29391: NVRAM_PHB_PBAPC_NAME_ORDER */
        buffer[ 45] = def_buf[ 45];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ADUPS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_double_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_double to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_double_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
	 nvram_get_default_value(NVRAM_EF_CACHE_DOUBLE_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BLUETOOTH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[120] = def_buf[120];     /* 35967: NVRAM_DISPCHAR_AVATAR_WPSS */
        buffer[121] = def_buf[121];
        buffer[122] = def_buf[122];
        buffer[123] = def_buf[123];
        buffer[124] = def_buf[124];
        buffer[125] = def_buf[125];
        buffer[126] = def_buf[126];
        buffer[127] = def_buf[127];
        buffer[ 80] = def_buf[ 80];     /* 35968: NARAM_DISPCHAR_AVATAR_ONOFF */
        buffer[ 81] = def_buf[ 81];
        buffer[ 82] = def_buf[ 82];
        buffer[ 83] = def_buf[ 83];
        buffer[ 84] = def_buf[ 84];
        buffer[ 85] = def_buf[ 85];
        buffer[ 86] = def_buf[ 86];
        buffer[ 87] = def_buf[ 87];
        buffer[200] = def_buf[200];     /* 35969: NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
        buffer[201] = def_buf[201];
        buffer[202] = def_buf[202];
        buffer[203] = def_buf[203];
        buffer[204] = def_buf[204];
        buffer[205] = def_buf[205];
        buffer[206] = def_buf[206];
        buffer[207] = def_buf[207];
        buffer[  8] = def_buf[  8];     /* 35970: NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
        buffer[  9] = def_buf[  9];
        buffer[ 10] = def_buf[ 10];
        buffer[ 11] = def_buf[ 11];
        buffer[ 12] = def_buf[ 12];
        buffer[ 13] = def_buf[ 13];
        buffer[ 14] = def_buf[ 14];
        buffer[ 15] = def_buf[ 15];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        buffer[  0] = def_buf[  0];     /* 37201: NVRAM_RTC_TIME */
        buffer[  1] = def_buf[  1];
        buffer[  2] = def_buf[  2];
        buffer[  3] = def_buf[  3];
        buffer[  4] = def_buf[  4];
        buffer[  5] = def_buf[  5];
        buffer[  6] = def_buf[  6];
        buffer[  7] = def_buf[  7];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MDI: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_BTCM: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        buffer[136] = def_buf[ 16];     /* 24474: NVRAM_PEN_CALIBRATION_VALUE1 = 24466: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1*/
        buffer[137] = def_buf[ 17];
        buffer[138] = def_buf[ 18];
        buffer[139] = def_buf[ 19];
        buffer[140] = def_buf[ 20];
        buffer[141] = def_buf[ 21];
        buffer[142] = def_buf[ 22];
        buffer[143] = def_buf[ 23];
        buffer[144] = def_buf[ 24];     /* 24475: NVRAM_PEN_CALIBRATION_VALUE2 = 24467: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2*/
        buffer[145] = def_buf[ 25];
        buffer[146] = def_buf[ 26];
        buffer[147] = def_buf[ 27];
        buffer[148] = def_buf[ 28];
        buffer[149] = def_buf[ 29];
        buffer[150] = def_buf[ 30];
        buffer[151] = def_buf[ 31];
        buffer[152] = def_buf[ 32];     /* 24476: NVRAM_PEN_CALIBRATION_VALUE3 = 24468: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3*/
        buffer[153] = def_buf[ 33];
        buffer[154] = def_buf[ 34];
        buffer[155] = def_buf[ 35];
        buffer[156] = def_buf[ 36];
        buffer[157] = def_buf[ 37];
        buffer[158] = def_buf[ 38];
        buffer[159] = def_buf[ 39];
        buffer[160] = def_buf[ 40];     /* 24477: NVRAM_PEN_CALIBRATION_VALUE4 = 24469: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4*/
        buffer[161] = def_buf[ 41];
        buffer[162] = def_buf[ 42];
        buffer[163] = def_buf[ 43];
        buffer[164] = def_buf[ 44];
        buffer[165] = def_buf[ 45];
        buffer[166] = def_buf[ 46];
        buffer[167] = def_buf[ 47];
        buffer[168] = def_buf[ 48];     /* 24478: NVRAM_PEN_CALIBRATION_VALUE5 = 24470: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5*/
        buffer[169] = def_buf[ 49];
        buffer[170] = def_buf[ 50];
        buffer[171] = def_buf[ 51];
        buffer[172] = def_buf[ 52];
        buffer[173] = def_buf[ 53];
        buffer[174] = def_buf[ 54];
        buffer[175] = def_buf[ 55];
        buffer[176] = def_buf[ 56];     /* 24479: NVRAM_PEN_CALIBRATION_VALUE6 = 24471: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6*/
        buffer[177] = def_buf[ 57];
        buffer[178] = def_buf[ 58];
        buffer[179] = def_buf[ 59];
        buffer[180] = def_buf[ 60];
        buffer[181] = def_buf[ 61];
        buffer[182] = def_buf[ 62];
        buffer[183] = def_buf[ 63];
        buffer[184] = def_buf[ 64];     /* 24480: NVRAM_PEN_CALIBRATION_VALUE7 = 24472: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7*/
        buffer[185] = def_buf[ 65];
        buffer[186] = def_buf[ 66];
        buffer[187] = def_buf[ 67];
        buffer[188] = def_buf[ 68];
        buffer[189] = def_buf[ 69];
        buffer[190] = def_buf[ 70];
        buffer[191] = def_buf[ 71];
        buffer[192] = def_buf[ 72];     /* 24481: NVRAM_PEN_CALIBRATION_VALUE8 = 24473: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8*/
        buffer[193] = def_buf[ 73];
        buffer[194] = def_buf[ 74];
        buffer[195] = def_buf[ 75];
        buffer[196] = def_buf[ 76];
        buffer[197] = def_buf[ 77];
        buffer[198] = def_buf[ 78];
        buffer[199] = def_buf[ 79];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_DATETIME_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_REMINDER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ADUPS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}


