/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_cache_nvram_editor.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   03 13 2011 yan.liang
 *
 *******************************************************************************/
/********************************************************
 *  This file is generated automatically by resource gen
 *  Please do not modify it here manually 
 ***********************************************************/
#ifndef MMI_RP_MMI_CACHE_NVRAM_EDITOR_H
#define MMI_RP_MMI_CACHE_NVRAM_EDITOR_H



/***********************************************************************
 ***  This is a nvram data item bit level description for meta tools nvram editor
 ***
 ***  Logical Data Item ID : NVRAM_EF_CACHE_BYTE_LID
 ***
 ***  Module:
 ***
 ***  Description:
 ***
 ***  Maintainer:
 ***
 ***********************************************************************/
LID_BIT VER_LID(NVRAM_EF_CACHE_BYTE_LID)
    nvram_cache_byte_struct * NVRAM_CACHE_TOTAL
    {
        Cachebyte:"1-byte parameter setting";
        Cachebyte[  0]
        {
            NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE_byte0:8 "Clam Back to Idle"
            {
            };
        };
        Cachebyte[  1]
        {
            NVRAM_CALLSET_FLIP_TO_MUTE_CALL_byte0:8 "Flip to mute call"
            {
            };
        };
        Cachebyte[  2]
        {
            NVRAM_WC_DST_byte0:8 "Current foreign city daylight saving"
            {
            };
        };
        Cachebyte[  3]
        {
            NVRAM_SETTING_LANG_byte0:8 "Current language"
            {
            };
        };
        Cachebyte[  4]
        {
            NVRAM_SETTING_PICTURE_QUALITY_byte0:8 "Picture Quality"
            {
            };
        };
        Cachebyte[  5]
        {
            NVRAM_SMS_MISCELL_SETTING_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[  6]
        {
            GPS_TIME_SYNC_MODE_byte0:8 "Gps time sync mode"
            {
            };
        };
        Cachebyte[  7]
        {
            NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[  8]
        {
            NVRAM_MRE_SRV_DA_IS_WIFI_ONLY_byte0:8 "MRE Dataaccount only use wifi"
            {
            };
        };
        Cachebyte[  9]
        {
            NVRAM_BT_POWER_STATUS_byte0:8 "Bluetooth setting"
            {
            };
        };
        Cachebyte[ 10]
        {
            NVRAM_PHB_SAVE_CONTACT_NOTIFY_byte0:8 "PHB_SAVE_NOTIFY"
            {
            };
        };
        Cachebyte[ 11]
        {
            NVRAM_NETSET_3G_CAPACITY_SIM_byte0:8 "Network 3g capacity sim card"
            {
            };
        };
        Cachebyte[ 12]
        {
            NVRAM_IMGVIEW_VIEW_SYTLE_byte0:8 "ImageViewer"
            {
            };
        };
        Cachebyte[ 13]
        {
            NVRAM_PHNSET_LIVE_WALLPAPER_byte0:8 "Live Wallpaper setting"
            {
            };
        };
        Cachebyte[ 14]
        {
            NVRAM_SETTING_AUTOKEYPADLOCK_TIME_byte0:8 "Auto KeyPad Lock Timer"
            {
            };
        };
        Cachebyte[ 15]
        {
            CURRENT_CITY_byte0:8 "Current home city"
            {
            };
        };
        Cachebyte[ 16]
        {
            NVRAM_IME_AUTO_COMPLETION_FLAG_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 17]
        {
            NVRAM_SETTING_HANDWRITING_ON_byte0:8 "nvram handwriting on"
            {
            };
        };
        Cachebyte[ 18]
        {
            NVRAM_EF_FMGR_SORT_OPTION_LID_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 19]
        {
            NVRAM_WALLPAPER_ROTATE_STATUS_byte0:8 "wallpaper rotate status"
            {
            };
        };
        Cachebyte[ 20]
        {
            NVRAM_SSC_DISABLE_FLAG_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 21]
        {
            NVRAM_REMINDER_TURNOVER_SENSOR_STATE_byte0:8 "current value 0,1"
            {
            };
        };
        Cachebyte[ 22]
        {
            NVRAM_SETTING_SPEED_DIAL_byte0:8 "Speed dial status"
            {
            };
        };
        Cachebyte[ 23]
        {
            RESTORE_DEFAULT_OWNER_NO_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 24]
        {
            NVRAM_CALLSET_QUICK_END_FLAG_byte0:8 "Auto quick end"
            {
            };
        };
        Cachebyte[ 25]
        {
            NVRAM_BYTE_LED_SETTING_byte0:8 "LED On/Off"
            {
            };
        };
        Cachebyte[ 26]
        {
            NVRAM_PHB_SPEAK_NAME_ON_OFF_byte0:8 "PHB_SPEAK_NAME"
            {
            };
        };
        Cachebyte[ 27]
        {
            NVRAM_SETTING_STROKE_COLOR_INDEX_byte0:8 "pen stroke color index"
            {
            };
        };
        Cachebyte[ 28]
        {
            NVRAM_AUDPLY_SINGLE_VOL_byte0:8 "Audio player"
            {
            };
        };
        Cachebyte[ 29]
        {
            NVRAM_CALLSET_REDIAL_byte0:8 "Auto redial mode"
            {
            };
        };
        Cachebyte[ 30]
        {
            NVRAM_GPS_PAYLOAD_STORAGE_byte0:8 "NVRAM_GPS_PAYLOAD_STORAGE"
            {
            };
        };
        Cachebyte[ 31]
        {
            NVRAM_PHB_NAME_DISPLAY_TYPE_byte0:8 "Phonebook name display type"
            {
            };
        };
        Cachebyte[ 32]
        {
            NVRAM_CALLSET_CALL_TIME_DISPLAY_byte0:8 "Call time display"
            {
            };
        };
        Cachebyte[ 33]
        {
            NVRAM_SMS_ACTIVE_PROFILE_INDEX_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 34]
        {
            NVRAM_SRV_SNDREC_QUALITY_byte0:8 "The record quality of sound recorder"
            {
            };
        };
        Cachebyte[ 35]
        {
            FOREIGN_CITY_byte0:8 "Current foreign city"
            {
            };
        };
        Cachebyte[ 36]
        {
            TIME_FORMAT_byte0:8 "Time format"
            {
            };
        };
        Cachebyte[ 37]
        {
            RESTORE_DEFAULT_TIME_FORMAT_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 38]
        {
            NVRAM_SETTING_DT_DST_byte0:8 "Current home city daylight saving"
            {
            };
        };
        Cachebyte[ 39]
        {
            NVRAM_BYTE_COVER_CLOSE_REJECT_CALL_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 40]
        {
            RESTORE_DEFAULT_AUTOUPDATE_TIME_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 41]
        {
            NVRAM_SETTING_PEN_SPEED_byte0:8 "pen speed"
            {
            };
        };
        Cachebyte[ 42]
        {
            NVRAM_SETTING_PEN_WIDTH_byte0:8 "pen trace width"
            {
            };
        };
        Cachebyte[ 43]
        {
            NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE_byte0:8 "Previouse RF mode for preferred mode switch"
            {
            };
        };
        Cachebyte[ 44]
        {
            NVRAM_IDLE_DIALER_SEARCH_SETTING_byte0:8 "Dialer search on / off"
            {
            };
        };
        Cachebyte[ 45]
        {
            NVRAM_PHNSET_MAIN_MENU_STYLE_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 46]
        {
            NVRAM_SETTING_CONTRAST_SUBLCD_LEVEL_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 47]
        {
            DATE_FORMAT_byte0:8 "Date format"
            {
            };
        };
        Cachebyte[ 48]
        {
            RESTORE_DEFAULT_DATE_FORMAT_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 49]
        {
            NRRAM_GPS_LOGGING_SWITCH_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 50]
        {
            NVRAM_PHB_STARTUP_COPY_SIM2_byte0:8 "PHB_STARTUP_COPY_2"
            {
            };
        };
        Cachebyte[ 51]
        {
            NVRAM_PHB_STARTUP_COPY_SIM3_byte0:8 "PHB_STARTUP_COPY_3"
            {
            };
        };
        Cachebyte[ 52]
        {
            NVRAM_PHB_STARTUP_COPY_SIM4_byte0:8 "PHB_STARTUP_COPY_4"
            {
            };
        };
        Cachebyte[ 53]
        {
            NVRAM_IME_INPUT_PATTERN_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 54]
        {
            NVRAM_CALLSET_TAP_TAP_TO_RECORD_IN_CALL_byte0:8 "Tap Tap to record in call"
            {
            };
        };
        Cachebyte[ 55]
        {
            NVRAM_PHB_STARTUP_COPY_SIM_byte0:8 "PHB_STARTUP_COPY_1"
            {
            };
        };
        Cachebyte[ 56]
        {
            NVRAM_UPDATE_DATETIME_MODE_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 57]
        {
            NVRAM_PROFILES_LASTACTIVATED_byte0:8 "User profiles"
            {
            };
        };
        Cachebyte[ 58]
        {
            NVRAM_SETTING_LANGUAGE_FOLLOW_VK_byte0:8 "language follow vk, default value is IME_WRITING_LANG_ABC"
            {
            };
        };
        Cachebyte[ 59]
        {
            NVRAM_BYTE_BL_SETTING_LEVEL_byte0:8 "Backlight Level"
            {
            };
        };
        Cachebyte[ 60]
        {
            NVRAM_SETTING_OWNER_NO_byte0:8 "show owner number in idle status"
            {
            };
        };
        Cachebyte[ 61]
        {
            NVRAM_CALLSET_CTR_MODE_byte0:8 "Call time reminder mode"
            {
            };
        };
        Cachebyte[ 62]
        {
            NVRAM_DOWNLOAD_CITY1_byte0:8 "sub lcd city 1"
            {
            };
        };
        Cachebyte[ 63]
        {
            NVRAM_DOWNLOAD_CITY2_byte0:8 "sub lcd city 2"
            {
            };
        };
        Cachebyte[ 64]
        {
            NVRAM_DEFAULT_USB_APP_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 65]
        {
            NVRAM_EF_SENSOR_UI_ROTATION_SWITCH_byte0:8 "UI rotation is on"
            {
            };
        };
        Cachebyte[ 66]
        {
            NVRAM_IME_SMART_MODE_CONFIG_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 67]
        {
            NVRAM_DT_SEP_FORMAT_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 68]
        {
            BT_BQB_TEST_byte0:8 "BQB TEST flag"
            {
            };
        };
        Cachebyte[ 69]
        {
            NVRAM_SETTING_CONTRAST_LEVEL_byte0:8 "LCD contrast"
            {
            };
        };
        Cachebyte[ 70]
        {
            NVRAM_IME_VIBRATION_FLAG_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 71]
        {
            NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 72]
        {
            NVRAM_SRV_SNDREC_STORAGE_byte0:8 "The storage location of sound recorder"
            {
            };
        };
        Cachebyte[ 73]
        {
            NVRAM_DUALMODE_MODE_SWITCH_TYPE_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 74]
        {
            NVRAM_IME_SOUND_FEEDBACK_FLAG_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 75]
        {
            NVRAM_NETSET_PREFERRED_MODE_byte0:8 "Current preferred mode"
            {
            };
        };
        Cachebyte[ 76]
        {
            NVRAM_HDSET_MODE_VOICE_LEVEL_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 77]
        {
            NVRAM_BT_RECEIVE_DRIVE_byte0:8 "Bluetooth Storage"
            {
            };
        };
        Cachebyte[ 78]
        {
            NVRAM_AUTO_VM_SETTING_AUTO_VM_byte0:8 "Sound recorder"
            {
            };
        };
        Cachebyte[ 79]
        {
            NVRAM_LDSPK_MODE_VOICE_LEVEL_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 80]
        {
            NVRAM_BT_RECEIVE_DRIVE_ASK_byte0:8 "Bluetooth Storage"
            {
            };
        };
        Cachebyte[ 81]
        {
            NVRAM_SETTING_AUTOKEYPADLOCK_byte0:8 "Auto KeyPad Lock Status"
            {
            };
        };
        Cachebyte[ 82]
        {
            NVRAM_NORMAL_MODE_VOICE_LEVEL_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 83]
        {
            SRV_DT_TIME_ZONE_byte0:8 "srv date time tz"
            {
            };
        };
        Cachebyte[ 84]
        {
            NVRAM_SETTING_STATUS_DT_TIME_byte0:8 "show date and time in idle status"
            {
            };
        };
        Cachebyte[ 85]
        {
            NVRAM_PROFILES_ACTIVATED_byte0:8 "User profiles"
            {
            };
        };
        Cachebyte[ 86]
        {
            NVRAM_IME_AUTO_CAPITALIZATION_FLAG_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 87]
        {
            NVRAM_IME_AUTO_SPACE_FLAG_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 88]
        {
            NVRAM_SETTING_AUTOUPDATE_DT_TIME_STATUS_byte0:8 "auto update date and time state"
            {
            };
        };
        Cachebyte[ 89]
        {
            NVRAM_ADUPS_SETTING_LID_byte0:8 "ADUPS REMIDER SET"
            {
            };
        };
        Cachebyte[ 90]
        {
            NVRAM_BYTE_COVER_CLOSE_KEYPAD_LOCK_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 91]
        {
            NVRAM_AUTOUPDATE_DT_STATUS_byte0:8 "Byte Cache"
            {
            };
        };
        Cachebyte[ 92]
        {
            NVRAM_IDLE_DIALER_TTS_SETTING_byte0:8 "TTS setting on / off"
            {
            };
        };
        Cachebyte[ 93]
        {
            NVRAM_CALLSET_ANSWER_MODE_byte0:8 "Answer mode"
            {
            };
        };
    };



/***********************************************************************
 ***  This is a nvram data item bit level description for meta tools nvram editor
 ***
 ***  Logical Data Item ID : NVRAM_EF_CACHE_SHORT_LID
 ***
 ***  Module:
 ***
 ***  Description:
 ***
 ***  Maintainer:
 ***
 ***********************************************************************/
LID_BIT VER_LID(NVRAM_EF_CACHE_SHORT_LID)
    nvram_cache_short_struct * NVRAM_CACHE_TOTAL
    {
        Cacheshort:"2-byte parameter setting";
        Cacheshort[  0]
        {
            NVRAM_SETTING_PREFER_INPUT_METHOD_byte0:8 "current preferred input method"
            {
            };
            NVRAM_SETTING_PREFER_INPUT_METHOD_byte1:8 "current preferred input method"
            {
            };
        };
        Cacheshort[  1]
        {
            NVRAM_SMS_CONCAT_MSG_REF_VALUE_byte0:8 "Short Cache"
            {
            };
            NVRAM_SMS_CONCAT_MSG_REF_VALUE_byte1:8 "Short Cache"
            {
            };
        };
        Cacheshort[  2]
        {
            NVRAM_CURRENT_POWER_OFF_DISPLAY_byte0:8 "current power off display"
            {
            };
            NVRAM_CURRENT_POWER_OFF_DISPLAY_byte1:8 "current power off display"
            {
            };
        };
        Cacheshort[  3]
        {
            NVRAM_SETTING_WRITING_LANG_byte0:8 "current writing language value"
            {
            };
            NVRAM_SETTING_WRITING_LANG_byte1:8 "current writing language value"
            {
            };
        };
        Cacheshort[  4]
        {
            NVRAM_CURRENT_POWER_ON_DISPLAY_byte0:8 "current power on display"
            {
            };
            NVRAM_CURRENT_POWER_ON_DISPLAY_byte1:8 "current power on display"
            {
            };
        };
        Cacheshort[  5]
        {
            NVRAM_CALLSET_QUICK_END_TIME_byte0:8 "Auto quick end duration"
            {
            };
            NVRAM_CALLSET_QUICK_END_TIME_byte1:8 "Auto quick end duration"
            {
            };
        };
        Cacheshort[  6]
        {
            NVRAM_PHB_STORAGE_LOCATION_byte0:8 "Phonebook prefer storage"
            {
            };
            NVRAM_PHB_STORAGE_LOCATION_byte1:8 "Phonebook prefer storage"
            {
            };
        };
        Cacheshort[  7]
        {
            NVRAM_FRN_TIMEZONE_byte0:8 "current foreign city time zone"
            {
            };
            NVRAM_FRN_TIMEZONE_byte1:8 "current foreign city time zone"
            {
            };
        };
        Cacheshort[  8]
        {
            RESTORE_PREFER_INPUT_METHOD_byte0:8 "Short Cache"
            {
            };
            RESTORE_PREFER_INPUT_METHOD_byte1:8 "Short Cache"
            {
            };
        };
        Cacheshort[  9]
        {
            RESTORE_DEFAULT_SETWALLPAPER_SUB_byte0:8 "Short Cache"
            {
            };
            RESTORE_DEFAULT_SETWALLPAPER_SUB_byte1:8 "Short Cache"
            {
            };
        };
        Cacheshort[ 10]
        {
            NVRAM_BYTE_BL_SETTING_HFTIME_byte0:8 "Backlight timer"
            {
            };
            NVRAM_BYTE_BL_SETTING_HFTIME_byte1:8 "Backlight timer"
            {
            };
        };
        Cacheshort[ 11]
        {
            NVRAM_PHB_VCARD_VERSION_byte0:8 "VCARD VERSION"
            {
            };
            NVRAM_PHB_VCARD_VERSION_byte1:8 "VCARD VERSION"
            {
            };
        };
        Cacheshort[ 12]
        {
            NVRAM_SETTING_ENABLED_WRITING_LANGUAGE_byte0:8 "Double cache"
            {
            };
            NVRAM_SETTING_ENABLED_WRITING_LANGUAGE_byte1:8 "Double cache"
            {
            };
        };
        Cacheshort[ 13]
        {
            NVRAM_RESTORE_POWER_OFF_DISPLAY_byte0:8 "Short Cache"
            {
            };
            NVRAM_RESTORE_POWER_OFF_DISPLAY_byte1:8 "Short Cache"
            {
            };
        };
        Cacheshort[ 14]
        {
            NVRAM_PHB_NAME_LIST_FILTER_byte0:8 "PHB_NLF"
            {
            };
            NVRAM_PHB_NAME_LIST_FILTER_byte1:8 "PHB_NLF"
            {
            };
        };
        Cacheshort[ 15]
        {
            NVRAM_POWER_ON_DISPLAY_SUCCESS_byte0:8 "Short Cache"
            {
            };
            NVRAM_POWER_ON_DISPLAY_SUCCESS_byte1:8 "Short Cache"
            {
            };
        };
        Cacheshort[ 16]
        {
            NVRAM_CALLSET_CTR_TIME_byte0:8 "Call time reminder time"
            {
            };
            NVRAM_CALLSET_CTR_TIME_byte1:8 "Call time reminder time"
            {
            };
        };
        Cacheshort[ 17]
        {
            RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER_byte0:8 "Short Cache"
            {
            };
            RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER_byte1:8 "Short Cache"
            {
            };
        };
        Cacheshort[ 18]
        {
            NVRAM_TIMEZONE_byte0:8 "Current time zone value"
            {
            };
            NVRAM_TIMEZONE_byte1:8 "Current time zone value"
            {
            };
        };
        Cacheshort[ 19]
        {
            NVRAM_RESTORE_POWER_ON_DISPLAY_byte0:8 "Short Cache"
            {
            };
            NVRAM_RESTORE_POWER_ON_DISPLAY_byte1:8 "Short Cache"
            {
            };
        };
        Cacheshort[ 20]
        {
            NVRAM_SETTING_WRITING_LANG_SUB_byte0:8 "current sub writing language value"
            {
            };
            NVRAM_SETTING_WRITING_LANG_SUB_byte1:8 "current sub writing language value"
            {
            };
        };
        Cacheshort[ 21]
        {
            NVRAM_IMGVIEW_STORAGE_byte0:8 "Image Viewer storage"
            {
            };
            NVRAM_IMGVIEW_STORAGE_byte1:8 "Image Viewer storage"
            {
            };
        };
        Cacheshort[ 22]
        {
            NVRAM_PHB_PBAPC_NAME_ORDER_byte0:8 "PBAPC NAME ORDER"
            {
            };
            NVRAM_PHB_PBAPC_NAME_ORDER_byte1:8 "PBAPC NAME ORDER"
            {
            };
        };
        Cacheshort[ 23]
        {
            NVRAM_FUNANDGAMES_SETWALLPAPER_byte0:8 "current wallpaper id"
            {
            };
            NVRAM_FUNANDGAMES_SETWALLPAPER_byte1:8 "current wallpaper id"
            {
            };
        };
        Cacheshort[ 24]
        {
            NVRAM_SETWALLPAPER_SUB_byte0:8 "current sub wallpaper id"
            {
            };
            NVRAM_SETWALLPAPER_SUB_byte1:8 "current sub wallpaper id"
            {
            };
        };
    };



/***********************************************************************
 ***  This is a nvram data item bit level description for meta tools nvram editor
 ***
 ***  Logical Data Item ID : NVRAM_EF_CACHE_DOUBLE_LID
 ***
 ***  Module:
 ***
 ***  Description:
 ***
 ***  Maintainer:
 ***
 ***********************************************************************/
LID_BIT VER_LID(NVRAM_EF_CACHE_DOUBLE_LID)
    nvram_cache_double_struct * NVRAM_CACHE_TOTAL
    {
        Cachedouble:"8-byte parameter setting";
        Cachedouble[  0]
        {
            NVRAM_RTC_TIME_byte0:8 "Curr RTC Sec Cache"
            {
            };
            NVRAM_RTC_TIME_byte1:8 "Curr RTC Sec Cache"
            {
            };
            NVRAM_RTC_TIME_byte2:8 "Curr RTC Sec Cache"
            {
            };
            NVRAM_RTC_TIME_byte3:8 "Curr RTC Sec Cache"
            {
            };
            NVRAM_RTC_TIME_byte4:8 "Curr RTC Sec Cache"
            {
            };
            NVRAM_RTC_TIME_byte5:8 "Curr RTC Sec Cache"
            {
            };
            NVRAM_RTC_TIME_byte6:8 "Curr RTC Sec Cache"
            {
            };
            NVRAM_RTC_TIME_byte7:8 "Curr RTC Sec Cache"
            {
            };
        };
        Cachedouble[  1]
        {
            NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM_byte0:8 "pwr on and off serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM_byte1:8 "pwr on and off serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM_byte2:8 "pwr on and off serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM_byte3:8 "pwr on and off serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM_byte4:8 "pwr on and off serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM_byte5:8 "pwr on and off serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM_byte6:8 "pwr on and off serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM_byte7:8 "pwr on and off serial num"
            {
            };
        };
        Cachedouble[  2]
        {
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1_byte0:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1_byte1:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1_byte2:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1_byte3:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1_byte4:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1_byte5:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1_byte6:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1_byte7:8 "Double cache"
            {
            };
        };
        Cachedouble[  3]
        {
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2_byte0:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2_byte1:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2_byte2:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2_byte3:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2_byte4:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2_byte5:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2_byte6:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2_byte7:8 "Double cache"
            {
            };
        };
        Cachedouble[  4]
        {
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3_byte0:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3_byte1:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3_byte2:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3_byte3:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3_byte4:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3_byte5:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3_byte6:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3_byte7:8 "Double cache"
            {
            };
        };
        Cachedouble[  5]
        {
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4_byte0:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4_byte1:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4_byte2:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4_byte3:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4_byte4:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4_byte5:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4_byte6:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4_byte7:8 "Double cache"
            {
            };
        };
        Cachedouble[  6]
        {
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5_byte0:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5_byte1:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5_byte2:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5_byte3:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5_byte4:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5_byte5:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5_byte6:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5_byte7:8 "Double cache"
            {
            };
        };
        Cachedouble[  7]
        {
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6_byte0:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6_byte1:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6_byte2:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6_byte3:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6_byte4:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6_byte5:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6_byte6:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6_byte7:8 "Double cache"
            {
            };
        };
        Cachedouble[  8]
        {
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7_byte0:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7_byte1:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7_byte2:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7_byte3:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7_byte4:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7_byte5:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7_byte6:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7_byte7:8 "Double cache"
            {
            };
        };
        Cachedouble[  9]
        {
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8_byte0:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8_byte1:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8_byte2:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8_byte3:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8_byte4:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8_byte5:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8_byte6:8 "Double cache"
            {
            };
            NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8_byte7:8 "Double cache"
            {
            };
        };
        Cachedouble[ 10]
        {
            NARAM_DISPCHAR_AVATAR_ONOFF_byte0:8 "avatar pwr on and off setting"
            {
            };
            NARAM_DISPCHAR_AVATAR_ONOFF_byte1:8 "avatar pwr on and off setting"
            {
            };
            NARAM_DISPCHAR_AVATAR_ONOFF_byte2:8 "avatar pwr on and off setting"
            {
            };
            NARAM_DISPCHAR_AVATAR_ONOFF_byte3:8 "avatar pwr on and off setting"
            {
            };
            NARAM_DISPCHAR_AVATAR_ONOFF_byte4:8 "avatar pwr on and off setting"
            {
            };
            NARAM_DISPCHAR_AVATAR_ONOFF_byte5:8 "avatar pwr on and off setting"
            {
            };
            NARAM_DISPCHAR_AVATAR_ONOFF_byte6:8 "avatar pwr on and off setting"
            {
            };
            NARAM_DISPCHAR_AVATAR_ONOFF_byte7:8 "avatar pwr on and off setting"
            {
            };
        };
        Cachedouble[ 11]
        {
            NVRAM_MRE_SRV_DA_SIM1_byte0:8 "MRE Dataaccount SIM1"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_byte1:8 "MRE Dataaccount SIM1"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_byte2:8 "MRE Dataaccount SIM1"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_byte3:8 "MRE Dataaccount SIM1"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_byte4:8 "MRE Dataaccount SIM1"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_byte5:8 "MRE Dataaccount SIM1"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_byte6:8 "MRE Dataaccount SIM1"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_byte7:8 "MRE Dataaccount SIM1"
            {
            };
        };
        Cachedouble[ 12]
        {
            NVRAM_MRE_SRV_DA_SIM2_byte0:8 "MRE Dataaccount SIM2"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_byte1:8 "MRE Dataaccount SIM2"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_byte2:8 "MRE Dataaccount SIM2"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_byte3:8 "MRE Dataaccount SIM2"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_byte4:8 "MRE Dataaccount SIM2"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_byte5:8 "MRE Dataaccount SIM2"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_byte6:8 "MRE Dataaccount SIM2"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_byte7:8 "MRE Dataaccount SIM2"
            {
            };
        };
        Cachedouble[ 13]
        {
            NVRAM_MRE_SRV_DA_SIM3_byte0:8 "MRE Dataaccount SIM3"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_byte1:8 "MRE Dataaccount SIM3"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_byte2:8 "MRE Dataaccount SIM3"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_byte3:8 "MRE Dataaccount SIM3"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_byte4:8 "MRE Dataaccount SIM3"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_byte5:8 "MRE Dataaccount SIM3"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_byte6:8 "MRE Dataaccount SIM3"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_byte7:8 "MRE Dataaccount SIM3"
            {
            };
        };
        Cachedouble[ 14]
        {
            NVRAM_MRE_SRV_DA_SIM4_byte0:8 "MRE Dataaccount SIM4"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_byte1:8 "MRE Dataaccount SIM4"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_byte2:8 "MRE Dataaccount SIM4"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_byte3:8 "MRE Dataaccount SIM4"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_byte4:8 "MRE Dataaccount SIM4"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_byte5:8 "MRE Dataaccount SIM4"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_byte6:8 "MRE Dataaccount SIM4"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_byte7:8 "MRE Dataaccount SIM4"
            {
            };
        };
        Cachedouble[ 15]
        {
            NVRAM_DISPCHAR_AVATAR_WPSS_byte0:8 "avatar wallpaper and ss setting"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_byte1:8 "avatar wallpaper and ss setting"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_byte2:8 "avatar wallpaper and ss setting"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_byte3:8 "avatar wallpaper and ss setting"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_byte4:8 "avatar wallpaper and ss setting"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_byte5:8 "avatar wallpaper and ss setting"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_byte6:8 "avatar wallpaper and ss setting"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_byte7:8 "avatar wallpaper and ss setting"
            {
            };
        };
        Cachedouble[ 16]
        {
            NVRAM_SRV_PROF_EXT_MELODY_BITS_byte0:8 "Profile Srv Ext Melody Bits"
            {
            };
            NVRAM_SRV_PROF_EXT_MELODY_BITS_byte1:8 "Profile Srv Ext Melody Bits"
            {
            };
            NVRAM_SRV_PROF_EXT_MELODY_BITS_byte2:8 "Profile Srv Ext Melody Bits"
            {
            };
            NVRAM_SRV_PROF_EXT_MELODY_BITS_byte3:8 "Profile Srv Ext Melody Bits"
            {
            };
            NVRAM_SRV_PROF_EXT_MELODY_BITS_byte4:8 "Profile Srv Ext Melody Bits"
            {
            };
            NVRAM_SRV_PROF_EXT_MELODY_BITS_byte5:8 "Profile Srv Ext Melody Bits"
            {
            };
            NVRAM_SRV_PROF_EXT_MELODY_BITS_byte6:8 "Profile Srv Ext Melody Bits"
            {
            };
            NVRAM_SRV_PROF_EXT_MELODY_BITS_byte7:8 "Profile Srv Ext Melody Bits"
            {
            };
        };
        Cachedouble[ 17]
        {
            NVRAM_PEN_CALIBRATION_VALUE1_byte0:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE1_byte1:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE1_byte2:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE1_byte3:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE1_byte4:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE1_byte5:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE1_byte6:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE1_byte7:8 "pen calibration value"
            {
            };
        };
        Cachedouble[ 18]
        {
            NVRAM_PEN_CALIBRATION_VALUE2_byte0:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE2_byte1:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE2_byte2:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE2_byte3:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE2_byte4:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE2_byte5:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE2_byte6:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE2_byte7:8 "pen calibration value"
            {
            };
        };
        Cachedouble[ 19]
        {
            NVRAM_PEN_CALIBRATION_VALUE3_byte0:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE3_byte1:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE3_byte2:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE3_byte3:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE3_byte4:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE3_byte5:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE3_byte6:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE3_byte7:8 "pen calibration value"
            {
            };
        };
        Cachedouble[ 20]
        {
            NVRAM_PEN_CALIBRATION_VALUE4_byte0:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE4_byte1:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE4_byte2:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE4_byte3:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE4_byte4:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE4_byte5:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE4_byte6:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE4_byte7:8 "pen calibration value"
            {
            };
        };
        Cachedouble[ 21]
        {
            NVRAM_PEN_CALIBRATION_VALUE5_byte0:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE5_byte1:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE5_byte2:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE5_byte3:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE5_byte4:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE5_byte5:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE5_byte6:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE5_byte7:8 "pen calibration value"
            {
            };
        };
        Cachedouble[ 22]
        {
            NVRAM_PEN_CALIBRATION_VALUE6_byte0:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE6_byte1:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE6_byte2:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE6_byte3:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE6_byte4:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE6_byte5:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE6_byte6:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE6_byte7:8 "pen calibration value"
            {
            };
        };
        Cachedouble[ 23]
        {
            NVRAM_PEN_CALIBRATION_VALUE7_byte0:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE7_byte1:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE7_byte2:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE7_byte3:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE7_byte4:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE7_byte5:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE7_byte6:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE7_byte7:8 "pen calibration value"
            {
            };
        };
        Cachedouble[ 24]
        {
            NVRAM_PEN_CALIBRATION_VALUE8_byte0:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE8_byte1:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE8_byte2:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE8_byte3:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE8_byte4:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE8_byte5:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE8_byte6:8 "pen calibration value"
            {
            };
            NVRAM_PEN_CALIBRATION_VALUE8_byte7:8 "pen calibration value"
            {
            };
        };
        Cachedouble[ 25]
        {
            NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM_byte0:8 "wallpaper and ss serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM_byte1:8 "wallpaper and ss serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM_byte2:8 "wallpaper and ss serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM_byte3:8 "wallpaper and ss serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM_byte4:8 "wallpaper and ss serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM_byte5:8 "wallpaper and ss serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM_byte6:8 "wallpaper and ss serial num"
            {
            };
            NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM_byte7:8 "wallpaper and ss serial num"
            {
            };
        };
        Cachedouble[ 26]
        {
            NVRAM_MRE_SRV_DA_SIM1_PX_byte0:8 "MRE Dataaccount SIM1 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_PX_byte1:8 "MRE Dataaccount SIM1 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_PX_byte2:8 "MRE Dataaccount SIM1 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_PX_byte3:8 "MRE Dataaccount SIM1 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_PX_byte4:8 "MRE Dataaccount SIM1 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_PX_byte5:8 "MRE Dataaccount SIM1 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_PX_byte6:8 "MRE Dataaccount SIM1 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM1_PX_byte7:8 "MRE Dataaccount SIM1 with proxy"
            {
            };
        };
        Cachedouble[ 27]
        {
            NVRAM_MRE_SRV_DA_SIM2_PX_byte0:8 "MRE Dataaccount SIM2 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_PX_byte1:8 "MRE Dataaccount SIM2 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_PX_byte2:8 "MRE Dataaccount SIM2 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_PX_byte3:8 "MRE Dataaccount SIM2 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_PX_byte4:8 "MRE Dataaccount SIM2 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_PX_byte5:8 "MRE Dataaccount SIM2 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_PX_byte6:8 "MRE Dataaccount SIM2 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM2_PX_byte7:8 "MRE Dataaccount SIM2 with proxy"
            {
            };
        };
        Cachedouble[ 28]
        {
            NVRAM_MRE_SRV_DA_SIM3_PX_byte0:8 "MRE Dataaccount SIM3 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_PX_byte1:8 "MRE Dataaccount SIM3 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_PX_byte2:8 "MRE Dataaccount SIM3 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_PX_byte3:8 "MRE Dataaccount SIM3 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_PX_byte4:8 "MRE Dataaccount SIM3 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_PX_byte5:8 "MRE Dataaccount SIM3 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_PX_byte6:8 "MRE Dataaccount SIM3 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM3_PX_byte7:8 "MRE Dataaccount SIM3 with proxy"
            {
            };
        };
        Cachedouble[ 29]
        {
            NVRAM_MRE_SRV_DA_SIM4_PX_byte0:8 "MRE Dataaccount SIM4 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_PX_byte1:8 "MRE Dataaccount SIM4 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_PX_byte2:8 "MRE Dataaccount SIM4 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_PX_byte3:8 "MRE Dataaccount SIM4 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_PX_byte4:8 "MRE Dataaccount SIM4 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_PX_byte5:8 "MRE Dataaccount SIM4 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_PX_byte6:8 "MRE Dataaccount SIM4 with proxy"
            {
            };
            NVRAM_MRE_SRV_DA_SIM4_PX_byte7:8 "MRE Dataaccount SIM4 with proxy"
            {
            };
        };
    };
#endif /* MMI_RP_MMI_CACHE_NVRAM_EDITOR_H */


