#ifndef _ADUPS_DEFINE_H_
#define _ADUPS_DEFINE_H_

#define ADUPS_FOTA_SERVICE_OEM			"SPROCOMM"
#define ADUPS_FOTA_SERVICE_MODEL         "HL300"
#define ADUPS_FOTA_SERVICE_PRODUCT_ID 		"1500888536"
#define ADUPS_FOTA_SERVICE_PRODUCT_SEC 		"342a67fcab0c4dbc837231c06a4cf643"
#define ADUPS_FOTA_SERVICE_DEVICE_TYPE 	"bicycle"
#define ADUPS_FOTA_SERVICE_PLATFORM 	"MTK2503AE"


#define ADUPS_FOTA_SDK_VER "IOT2.6_R40226"
#define ADUPS_FOTA_APP_VER "ADUPS_V2.6"
#define ADUPS_FOTA_SDK_MAX_MCU_NUM    5

#define ADUPS_FOTA_FILENAME1 "adups.bin-D"
#define ADUPS_FOTA_ADDRESS1   "0x10020000"
#define ADUPS_FOTA_FILENAME2 "MT3333.bin-F"
#define ADUPS_FOTA_ADDRESS2  "MCU1"

#define ADUPS_MAX_DELTA_NUM 2
#define ADUPS_PACKAGE_AREA_BASE 0x680000
#define ADUPS_PACKAGE_AREA_LEN  0x180000
#define ADUPS_BLOCK_SIZE  (32*1024)
#define ADUPS_LCD_NONE
#define ADUPS_DEVICE_NETWORKTYPE "2G"


#define ADUPS_REPORT_DL
//#define ADUPS_AUTO_TEST

#endif
