#ifndef _IPERF_TRC_GEN_H_
#define _IPERF_TRC_GEN_H_

// FUNC_IPERF_MAIN
#define FUNC_IPERF_MAIN_size "h"
#define FUNC_IPERF_MAIN FUNC_IPERF_MAIN__enum,FUNC_IPERF_MAIN_size

// FUNC_IPERF_SEND_MMI_REPORT_IND
#define FUNC_IPERF_SEND_MMI_REPORT_IND_size "d"
#define FUNC_IPERF_SEND_MMI_REPORT_IND FUNC_IPERF_SEND_MMI_REPORT_IND__enum,FUNC_IPERF_SEND_MMI_REPORT_IND_size

// FUNC_IPERF_SEND_MMI_RUN_CNF
#define FUNC_IPERF_SEND_MMI_RUN_CNF_size "d"
#define FUNC_IPERF_SEND_MMI_RUN_CNF FUNC_IPERF_SEND_MMI_RUN_CNF__enum,FUNC_IPERF_SEND_MMI_RUN_CNF_size

// FUNC_IPERF_INIT_SETTINGS
#define FUNC_IPERF_INIT_SETTINGS_size NULL
#define FUNC_IPERF_INIT_SETTINGS FUNC_IPERF_INIT_SETTINGS__enum,FUNC_IPERF_INIT_SETTINGS_size

// FUNC_IPERF_RUN
#define FUNC_IPERF_RUN_size "c"
#define FUNC_IPERF_RUN FUNC_IPERF_RUN__enum,FUNC_IPERF_RUN_size

// FUNC_SETTINGS_INITIALIZE
#define FUNC_SETTINGS_INITIALIZE_size NULL
#define FUNC_SETTINGS_INITIALIZE FUNC_SETTINGS_INITIALIZE__enum,FUNC_SETTINGS_INITIALIZE_size

// FUNC_SETTINGS_PARSEPARAMETERS
#define FUNC_SETTINGS_PARSEPARAMETERS_size NULL
#define FUNC_SETTINGS_PARSEPARAMETERS FUNC_SETTINGS_PARSEPARAMETERS__enum,FUNC_SETTINGS_PARSEPARAMETERS_size

// FUNC_CLIENT_INIT
#define FUNC_CLIENT_INIT_size NULL
#define FUNC_CLIENT_INIT FUNC_CLIENT_INIT__enum,FUNC_CLIENT_INIT_size

// FUNC_THREAD_START
#define FUNC_THREAD_START_size NULL
#define FUNC_THREAD_START FUNC_THREAD_START__enum,FUNC_THREAD_START_size

// FUNC_THREAD_JOINALL
#define FUNC_THREAD_JOINALL_size NULL
#define FUNC_THREAD_JOINALL FUNC_THREAD_JOINALL__enum,FUNC_THREAD_JOINALL_size

// FUNC_THREAD_RUN_WRAPPER
#define FUNC_THREAD_RUN_WRAPPER_size NULL
#define FUNC_THREAD_RUN_WRAPPER FUNC_THREAD_RUN_WRAPPER__enum,FUNC_THREAD_RUN_WRAPPER_size

// FUNC_SERVER_SPAWN
#define FUNC_SERVER_SPAWN_size NULL
#define FUNC_SERVER_SPAWN FUNC_SERVER_SPAWN__enum,FUNC_SERVER_SPAWN_size

// FUNC_CLIENT_SPAWN
#define FUNC_CLIENT_SPAWN_size NULL
#define FUNC_CLIENT_SPAWN FUNC_CLIENT_SPAWN__enum,FUNC_CLIENT_SPAWN_size

// FUNC_REPORTER_SPAWN
#define FUNC_REPORTER_SPAWN_size NULL
#define FUNC_REPORTER_SPAWN FUNC_REPORTER_SPAWN__enum,FUNC_REPORTER_SPAWN_size

// FUNC_LISTENER_SPAWN
#define FUNC_LISTENER_SPAWN_size NULL
#define FUNC_LISTENER_SPAWN FUNC_LISTENER_SPAWN__enum,FUNC_LISTENER_SPAWN_size

// FUNC_SETTINGS_DESTROY
#define FUNC_SETTINGS_DESTROY_size NULL
#define FUNC_SETTINGS_DESTROY FUNC_SETTINGS_DESTROY__enum,FUNC_SETTINGS_DESTROY_size

// FUNC_SETTINGS_INTERPRETE
#define FUNC_SETTINGS_INTERPRETE_size NULL
#define FUNC_SETTINGS_INTERPRETE FUNC_SETTINGS_INTERPRETE__enum,FUNC_SETTINGS_INTERPRETE_size

// FUNC_SERVER_SERVER
#define FUNC_SERVER_SERVER_size NULL
#define FUNC_SERVER_SERVER FUNC_SERVER_SERVER__enum,FUNC_SERVER_SERVER_size

// FUNC_SERVER_RUN
#define FUNC_SERVER_RUN_size NULL
#define FUNC_SERVER_RUN FUNC_SERVER_RUN__enum,FUNC_SERVER_RUN_size

// FUNC_SERVER_WRITE_UDP_ACKFIN
#define FUNC_SERVER_WRITE_UDP_ACKFIN_size NULL
#define FUNC_SERVER_WRITE_UDP_ACKFIN FUNC_SERVER_WRITE_UDP_ACKFIN__enum,FUNC_SERVER_WRITE_UDP_ACKFIN_size

// FUNC_SERVER_DESTRUCTOR
#define FUNC_SERVER_DESTRUCTOR_size NULL
#define FUNC_SERVER_DESTRUCTOR FUNC_SERVER_DESTRUCTOR__enum,FUNC_SERVER_DESTRUCTOR_size

// FUNC_INITREPORT
#define FUNC_INITREPORT_size NULL
#define FUNC_INITREPORT FUNC_INITREPORT__enum,FUNC_INITREPORT_size

// FUNC_GETTIMEOFDAY
#define FUNC_GETTIMEOFDAY_size NULL
#define FUNC_GETTIMEOFDAY FUNC_GETTIMEOFDAY__enum,FUNC_GETTIMEOFDAY_size

// FUNC_REPORTPACKET
#define FUNC_REPORTPACKET_size NULL
#define FUNC_REPORTPACKET FUNC_REPORTPACKET__enum,FUNC_REPORTPACKET_size

// FUNC_CLOSEREPORT
#define FUNC_CLOSEREPORT_size NULL
#define FUNC_CLOSEREPORT FUNC_CLOSEREPORT__enum,FUNC_CLOSEREPORT_size

// FUNC_IPERF_DELETE
#define FUNC_IPERF_DELETE_size NULL
#define FUNC_IPERF_DELETE FUNC_IPERF_DELETE__enum,FUNC_IPERF_DELETE_size

// FUNC_ENDREPORT
#define FUNC_ENDREPORT_size NULL
#define FUNC_ENDREPORT FUNC_ENDREPORT__enum,FUNC_ENDREPORT_size

// FUNC_CLIENT_CLIENT
#define FUNC_CLIENT_CLIENT_size NULL
#define FUNC_CLIENT_CLIENT FUNC_CLIENT_CLIENT__enum,FUNC_CLIENT_CLIENT_size

// FUNC_CLIENT_INITIATESERVER
#define FUNC_CLIENT_INITIATESERVER_size NULL
#define FUNC_CLIENT_INITIATESERVER FUNC_CLIENT_INITIATESERVER__enum,FUNC_CLIENT_INITIATESERVER_size

// FUNC_CLIENT_RUN
#define FUNC_CLIENT_RUN_size NULL
#define FUNC_CLIENT_RUN FUNC_CLIENT_RUN__enum,FUNC_CLIENT_RUN_size

// FUNC_CLIENT_WRITE_UDP_FIN
#define FUNC_CLIENT_WRITE_UDP_FIN_size NULL
#define FUNC_CLIENT_WRITE_UDP_FIN FUNC_CLIENT_WRITE_UDP_FIN__enum,FUNC_CLIENT_WRITE_UDP_FIN_size

// FUNC_CLIENT_DESTRUCTOR
#define FUNC_CLIENT_DESTRUCTOR_size NULL
#define FUNC_CLIENT_DESTRUCTOR FUNC_CLIENT_DESTRUCTOR__enum,FUNC_CLIENT_DESTRUCTOR_size

// FUNC_WRITE_IPERF_PATTERN
#define FUNC_WRITE_IPERF_PATTERN_size NULL
#define FUNC_WRITE_IPERF_PATTERN FUNC_WRITE_IPERF_PATTERN__enum,FUNC_WRITE_IPERF_PATTERN_size

// FUNC_CLIENT_CONNECT
#define FUNC_CLIENT_CONNECT_size NULL
#define FUNC_CLIENT_CONNECT FUNC_CLIENT_CONNECT__enum,FUNC_CLIENT_CONNECT_size

// FUNC_SOCKADDR_SETPORTANY
#define FUNC_SOCKADDR_SETPORTANY_size NULL
#define FUNC_SOCKADDR_SETPORTANY FUNC_SOCKADDR_SETPORTANY__enum,FUNC_SOCKADDR_SETPORTANY_size

// FUNC_SOCKADDR_REMOTEADDR
#define FUNC_SOCKADDR_REMOTEADDR_size NULL
#define FUNC_SOCKADDR_REMOTEADDR FUNC_SOCKADDR_REMOTEADDR__enum,FUNC_SOCKADDR_REMOTEADDR_size

// FUNC_SETSOCKETOPTIONS
#define FUNC_SETSOCKETOPTIONS_size NULL
#define FUNC_SETSOCKETOPTIONS FUNC_SETSOCKETOPTIONS__enum,FUNC_SETSOCKETOPTIONS_size

// FUNC_SOCKADDR_LOCALADDR
#define FUNC_SOCKADDR_LOCALADDR_size NULL
#define FUNC_SOCKADDR_LOCALADDR FUNC_SOCKADDR_LOCALADDR__enum,FUNC_SOCKADDR_LOCALADDR_size

// FUNC_SOCKET
#define FUNC_SOCKET_size "dcd"
#define FUNC_SOCKET FUNC_SOCKET__enum,FUNC_SOCKET_size

// FUNC_CLOSE
#define FUNC_CLOSE_size "d"
#define FUNC_CLOSE FUNC_CLOSE__enum,FUNC_CLOSE_size

// FUNC_BIND
#define FUNC_BIND_size "‚d"
#define FUNC_BIND FUNC_BIND__enum,FUNC_BIND_size

// FUNC_LISTEN
#define FUNC_LISTEN_size "‚d"
#define FUNC_LISTEN FUNC_LISTEN__enum,FUNC_LISTEN_size

// FUNC_ACCEPT
#define FUNC_ACCEPT_size "d"
#define FUNC_ACCEPT FUNC_ACCEPT__enum,FUNC_ACCEPT_size

// FUNC_CONNECT
#define FUNC_CONNECT_size "d"
#define FUNC_CONNECT FUNC_CONNECT__enum,FUNC_CONNECT_size

// FUNC_READ
#define FUNC_READ_size "d"
#define FUNC_READ FUNC_READ__enum,FUNC_READ_size

// FUNC_WRITE
#define FUNC_WRITE_size "d"
#define FUNC_WRITE FUNC_WRITE__enum,FUNC_WRITE_size

// FUNC_SEND
#define FUNC_SEND_size "d"
#define FUNC_SEND FUNC_SEND__enum,FUNC_SEND_size

// FUNC_SENDTO
#define FUNC_SENDTO_size "d"
#define FUNC_SENDTO FUNC_SENDTO__enum,FUNC_SENDTO_size

// FUNC_RECV
#define FUNC_RECV_size "d"
#define FUNC_RECV FUNC_RECV__enum,FUNC_RECV_size

// FUNC_RECVFROM
#define FUNC_RECVFROM_size "d"
#define FUNC_RECVFROM FUNC_RECVFROM__enum,FUNC_RECVFROM_size

// FUNC_SETSOCKOPT
#define FUNC_SETSOCKOPT_size "ƒd"
#define FUNC_SETSOCKOPT FUNC_SETSOCKOPT__enum,FUNC_SETSOCKOPT_size

// FUNC_SETSOCKOPT_HEX
#define FUNC_SETSOCKOPT_HEX_size "ƒd"
#define FUNC_SETSOCKOPT_HEX FUNC_SETSOCKOPT_HEX__enum,FUNC_SETSOCKOPT_HEX_size

// FUNC_GETSOCKOPT
#define FUNC_GETSOCKOPT_size "d"
#define FUNC_GETSOCKOPT FUNC_GETSOCKOPT__enum,FUNC_GETSOCKOPT_size

// FUNC_GETSOCKNAME
#define FUNC_GETSOCKNAME_size "d"
#define FUNC_GETSOCKNAME FUNC_GETSOCKNAME__enum,FUNC_GETSOCKNAME_size

// FUNC_GETPEERNAME
#define FUNC_GETPEERNAME_size "d"
#define FUNC_GETPEERNAME FUNC_GETPEERNAME__enum,FUNC_GETPEERNAME_size

// FUNC_SELECT
#define FUNC_SELECT_size NULL
#define FUNC_SELECT FUNC_SELECT__enum,FUNC_SELECT_size

// FUNC_FOPEN
#define FUNC_FOPEN_size NULL
#define FUNC_FOPEN FUNC_FOPEN__enum,FUNC_FOPEN_size

// FUNC_FCLOSE
#define FUNC_FCLOSE_size NULL
#define FUNC_FCLOSE FUNC_FCLOSE__enum,FUNC_FCLOSE_size

// FUNC_FREAD
#define FUNC_FREAD_size NULL
#define FUNC_FREAD FUNC_FREAD__enum,FUNC_FREAD_size

// FUNC_MALLOC
#define FUNC_MALLOC_size "d"
#define FUNC_MALLOC FUNC_MALLOC__enum,FUNC_MALLOC_size

// FUNC_FREE
#define FUNC_FREE_size NULL
#define FUNC_FREE FUNC_FREE__enum,FUNC_FREE_size

// FUNC_IPERF_STOP
#define FUNC_IPERF_STOP_size "d"
#define FUNC_IPERF_STOP FUNC_IPERF_STOP__enum,FUNC_IPERF_STOP_size

// FUNC_REPORTSERVERUDP
#define FUNC_REPORTSERVERUDP_size NULL
#define FUNC_REPORTSERVERUDP FUNC_REPORTSERVERUDP__enum,FUNC_REPORTSERVERUDP_size

// FUNC_REPORTER_PROCESS_REPORT
#define FUNC_REPORTER_PROCESS_REPORT_size NULL
#define FUNC_REPORTER_PROCESS_REPORT FUNC_REPORTER_PROCESS_REPORT__enum,FUNC_REPORTER_PROCESS_REPORT_size

// FUNC_THREAD_REST
#define FUNC_THREAD_REST_size NULL
#define FUNC_THREAD_REST FUNC_THREAD_REST__enum,FUNC_THREAD_REST_size

// FUNC_PROCESS_REPORT
#define FUNC_PROCESS_REPORT_size NULL
#define FUNC_PROCESS_REPORT FUNC_PROCESS_REPORT__enum,FUNC_PROCESS_REPORT_size

// FUNC_REPORTER_PRINT
#define FUNC_REPORTER_PRINT_size NULL
#define FUNC_REPORTER_PRINT FUNC_REPORTER_PRINT__enum,FUNC_REPORTER_PRINT_size

// FUNC_REPORTER_PRINTSTATS
#define FUNC_REPORTER_PRINTSTATS_size NULL
#define FUNC_REPORTER_PRINTSTATS FUNC_REPORTER_PRINTSTATS__enum,FUNC_REPORTER_PRINTSTATS_size

// FUNC_REPORTER_MULTISTATS
#define FUNC_REPORTER_MULTISTATS_size NULL
#define FUNC_REPORTER_MULTISTATS FUNC_REPORTER_MULTISTATS__enum,FUNC_REPORTER_MULTISTATS_size

// FUNC_REPORTER_REPORTSETTINGS
#define FUNC_REPORTER_REPORTSETTINGS_size NULL
#define FUNC_REPORTER_REPORTSETTINGS FUNC_REPORTER_REPORTSETTINGS__enum,FUNC_REPORTER_REPORTSETTINGS_size

// FUNC_LISTENER_LISTENER
#define FUNC_LISTENER_LISTENER_size NULL
#define FUNC_LISTENER_LISTENER FUNC_LISTENER_LISTENER__enum,FUNC_LISTENER_LISTENER_size

// FUNC_LISTENER_RUN
#define FUNC_LISTENER_RUN_size NULL
#define FUNC_LISTENER_RUN FUNC_LISTENER_RUN__enum,FUNC_LISTENER_RUN_size

// FUNC_LISTENER_ACCEPT
#define FUNC_LISTENER_ACCEPT_size NULL
#define FUNC_LISTENER_ACCEPT FUNC_LISTENER_ACCEPT__enum,FUNC_LISTENER_ACCEPT_size

// FUNC_LISTENER_LISTEN
#define FUNC_LISTENER_LISTEN_size NULL
#define FUNC_LISTENER_LISTEN FUNC_LISTENER_LISTEN__enum,FUNC_LISTENER_LISTEN_size

// FUNC_LISTENER_DESTRUCTOR
#define FUNC_LISTENER_DESTRUCTOR_size NULL
#define FUNC_LISTENER_DESTRUCTOR FUNC_LISTENER_DESTRUCTOR__enum,FUNC_LISTENER_DESTRUCTOR_size

// FUNC_REPORTSETTINGS
#define FUNC_REPORTSETTINGS_size NULL
#define FUNC_REPORTSETTINGS FUNC_REPORTSETTINGS__enum,FUNC_REPORTSETTINGS_size

// FUNC_SETTINGS_COPY
#define FUNC_SETTINGS_COPY_size NULL
#define FUNC_SETTINGS_COPY FUNC_SETTINGS_COPY__enum,FUNC_SETTINGS_COPY_size

// FUNC_IPERF_HOSTPRESENT
#define FUNC_IPERF_HOSTPRESENT_size NULL
#define FUNC_IPERF_HOSTPRESENT FUNC_IPERF_HOSTPRESENT__enum,FUNC_IPERF_HOSTPRESENT_size

// FUNC_IPERF_PUSHBACK
#define FUNC_IPERF_PUSHBACK_size NULL
#define FUNC_IPERF_PUSHBACK FUNC_IPERF_PUSHBACK__enum,FUNC_IPERF_PUSHBACK_size

// FUNC_SETTINGS_GENERATECLIENTSETTINGS
#define FUNC_SETTINGS_GENERATECLIENTSETTINGS_size NULL
#define FUNC_SETTINGS_GENERATECLIENTSETTINGS FUNC_SETTINGS_GENERATECLIENTSETTINGS__enum,FUNC_SETTINGS_GENERATECLIENTSETTINGS_size

// FUNC_SETSOCK_TCP_WINDOWSIZE
#define FUNC_SETSOCK_TCP_WINDOWSIZE_size "ƒd"
#define FUNC_SETSOCK_TCP_WINDOWSIZE FUNC_SETSOCK_TCP_WINDOWSIZE__enum,FUNC_SETSOCK_TCP_WINDOWSIZE_size

// FUNC_STAUT_RUN
#define FUNC_STAUT_RUN_size "„d"
#define FUNC_STAUT_RUN FUNC_STAUT_RUN__enum,FUNC_STAUT_RUN_size

// STATE_INTERRUPTED
#define STATE_INTERRUPTED_size NULL
#define STATE_INTERRUPTED STATE_INTERRUPTED__enum,STATE_INTERRUPTED_size

// STATE_TIME_END
#define STATE_TIME_END_size NULL
#define STATE_TIME_END STATE_TIME_END__enum,STATE_TIME_END_size

// STATE_DATA_END
#define STATE_DATA_END_size NULL
#define STATE_DATA_END STATE_DATA_END__enum,STATE_DATA_END_size

// STATE_CANNOT_READ
#define STATE_CANNOT_READ_size NULL
#define STATE_CANNOT_READ STATE_CANNOT_READ__enum,STATE_CANNOT_READ_size

// INFO_SET_GLOBAL_ACCOUNT_ID
#define INFO_SET_GLOBAL_ACCOUNT_ID_size "‚d"
#define INFO_SET_GLOBAL_ACCOUNT_ID INFO_SET_GLOBAL_ACCOUNT_ID__enum,INFO_SET_GLOBAL_ACCOUNT_ID_size

// INFO_RECV_EXT_Q
#define INFO_RECV_EXT_Q_size "h"
#define INFO_RECV_EXT_Q INFO_RECV_EXT_Q__enum,INFO_RECV_EXT_Q_size

// INFO_SET_ACCOUNT
#define INFO_SET_ACCOUNT_size "d"
#define INFO_SET_ACCOUNT INFO_SET_ACCOUNT__enum,INFO_SET_ACCOUNT_size

// INFO_SET_CLIENTMODE
#define INFO_SET_CLIENTMODE_size "c„d"
#define INFO_SET_CLIENTMODE INFO_SET_CLIENTMODE__enum,INFO_SET_CLIENTMODE_size

// INFO_SET_SERVERMODE
#define INFO_SET_SERVERMODE_size "c"
#define INFO_SET_SERVERMODE INFO_SET_SERVERMODE__enum,INFO_SET_SERVERMODE_size

// INFO_SET_UDPMODE
#define INFO_SET_UDPMODE_size "d"
#define INFO_SET_UDPMODE INFO_SET_UDPMODE__enum,INFO_SET_UDPMODE_size

// INFO_SET_LEN
#define INFO_SET_LEN_size "d"
#define INFO_SET_LEN INFO_SET_LEN__enum,INFO_SET_LEN_size

// INFO_SET_PORT
#define INFO_SET_PORT_size "d"
#define INFO_SET_PORT INFO_SET_PORT__enum,INFO_SET_PORT_size

// INFO_SET_WIN
#define INFO_SET_WIN_size "d"
#define INFO_SET_WIN INFO_SET_WIN__enum,INFO_SET_WIN_size

// INFO_SET_MSS
#define INFO_SET_MSS_size "d"
#define INFO_SET_MSS INFO_SET_MSS__enum,INFO_SET_MSS_size

// INFO_SET_BW
#define INFO_SET_BW_size "d"
#define INFO_SET_BW INFO_SET_BW__enum,INFO_SET_BW_size

// INFO_SET_NUM
#define INFO_SET_NUM_size "d"
#define INFO_SET_NUM INFO_SET_NUM__enum,INFO_SET_NUM_size

// INFO_SET_TIME
#define INFO_SET_TIME_size "d"
#define INFO_SET_TIME INFO_SET_TIME__enum,INFO_SET_TIME_size

// INFO_SET_TOS
#define INFO_SET_TOS_size "d"
#define INFO_SET_TOS INFO_SET_TOS__enum,INFO_SET_TOS_size

// INFO_SET_DUALTEST
#define INFO_SET_DUALTEST_size "c"
#define INFO_SET_DUALTEST INFO_SET_DUALTEST__enum,INFO_SET_DUALTEST_size

// INFO_ZERO_TID
#define INFO_ZERO_TID_size NULL
#define INFO_ZERO_TID INFO_ZERO_TID__enum,INFO_ZERO_TID_size

// INFO_GOT_MEM
#define INFO_GOT_MEM_size "ƒd"
#define INFO_GOT_MEM INFO_GOT_MEM__enum,INFO_GOT_MEM_size

// INFO_GETTIMEOFDAY
#define INFO_GETTIMEOFDAY_size "‚d"
#define INFO_GETTIMEOFDAY INFO_GETTIMEOFDAY__enum,INFO_GETTIMEOFDAY_size

// INFO_IPERF_STOP
#define INFO_IPERF_STOP_size "„d"
#define INFO_IPERF_STOP INFO_IPERF_STOP__enum,INFO_IPERF_STOP_size

// INFO_IPERF_SERVER_REPORT_INFO_BPS
#define INFO_IPERF_SERVER_REPORT_INFO_BPS_size "‚d"
#define INFO_IPERF_SERVER_REPORT_INFO_BPS INFO_IPERF_SERVER_REPORT_INFO_BPS__enum,INFO_IPERF_SERVER_REPORT_INFO_BPS_size

// WARN_MALLOC_ZERO
#define WARN_MALLOC_ZERO_size NULL
#define WARN_MALLOC_ZERO WARN_MALLOC_ZERO__enum,WARN_MALLOC_ZERO_size

// WARN_MSS_FAIL
#define WARN_MSS_FAIL_size "d"
#define WARN_MSS_FAIL WARN_MSS_FAIL__enum,WARN_MSS_FAIL_size

// WARN_MSS_NOTSET
#define WARN_MSS_NOTSET_size "‚d"
#define WARN_MSS_NOTSET WARN_MSS_NOTSET__enum,WARN_MSS_NOTSET_size

// ERROR_NONSUPPORT_MSG
#define ERROR_NONSUPPORT_MSG_size "h"
#define ERROR_NONSUPPORT_MSG ERROR_NONSUPPORT_MSG__enum,ERROR_NONSUPPORT_MSG_size

// ERROR_GOT_MEM_FAIL
#define ERROR_GOT_MEM_FAIL_size "‚d"
#define ERROR_GOT_MEM_FAIL ERROR_GOT_MEM_FAIL__enum,ERROR_GOT_MEM_FAIL_size

// ERROR_CLIENT_WITHOUT_REMOTE_ADDR
#define ERROR_CLIENT_WITHOUT_REMOTE_ADDR_size NULL
#define ERROR_CLIENT_WITHOUT_REMOTE_ADDR ERROR_CLIENT_WITHOUT_REMOTE_ADDR__enum,ERROR_CLIENT_WITHOUT_REMOTE_ADDR_size

// ERROR_SOCKET
#define ERROR_SOCKET_size "d"
#define ERROR_SOCKET ERROR_SOCKET__enum,ERROR_SOCKET_size

// ERROR_WARN_ERRNO
#define ERROR_WARN_ERRNO_size "‚sd"
#define ERROR_WARN_ERRNO ERROR_WARN_ERRNO__enum,ERROR_WARN_ERRNO_size


#endif // IPERF_TRC_GEN.H
